import Riesz2.S9896.Data
/-! Kernel check `chkG` of the slab S9896.
    Generated by `lean/gen_riesz2/emit_tcert.py` from `cert_slab_98_96_riesz2.json` (sha256 fa11d3b6b3610c6a…).
    Riesz s = 2 kernel `phi2 t = 1/(2-2t)`; format = upstream `TCert` (ThomsonGen/CertT.lean).
    Regenerate; do not edit. -/

open Real

section Riesz2_S9896_tc
namespace Riesz2
open ThomsonN7 ThomsonN7.Kron ThomsonN7.Kron.Ex ThomsonN7.Cert ThomsonN7.ThreePoint

theorem tc_s9896_G : tc_s9896.chkG = true := by decide +kernel

end Riesz2
end Riesz2_S9896_tc
