import Riesz2.S9896.ChkMeta
import Riesz2.S9896.ChkA
import Riesz2.S9896.ChkB
import Riesz2.S9896.ChkG
import Riesz2.Bridge
import Riesz2.MinorS9896
/-! Slab S9896: `ThomsonGen.SlabSpec phi2 -49/50 -24/25` from the checked packed certificate `tc_s9896`
and the 1-D minorants of `Riesz2.Minor.S9896` (identified through `scaledEq`).
Generated by lean/gen_riesz2/gen_spec2.py; do not edit. -/

open Real
namespace Riesz2
namespace S9896
open Minor ThomsonN7.Cert

theorem e_eq : tc_s9896.e = 189080971429930270720 := rfl
theorem lam_eq : tc_s9896.Lam = 18446744073709551616 := rfl
theorem an_eq : tc_s9896.an = -49 := rfl
theorem ad_eq : tc_s9896.ad = 50 := rfl
theorem bn_eq : tc_s9896.bn = -24 := rfl
theorem bd_eq : tc_s9896.bd = 25 := rfl
theorem lam_pos : 0 < tc_s9896.Lam := by rw [lam_eq]; norm_num
theorem alo_eq : tc_s9896.alo = (-49 / 50 : ℝ) := by
  unfold TCert.alo; rw [an_eq, ad_eq]; norm_num
theorem ahi_eq : tc_s9896.ahi = (-24 / 25 : ℝ) := by
  unfold TCert.ahi; rw [bn_eq, bd_eq]; norm_num
theorem ef_gt : (41 / 4 : ℝ) < tc_s9896.ef := by
  unfold TCert.ef; rw [e_eq, lam_eq]; norm_num
theorem eA : scaledEq Minor.S9896.HAd tc_s9896.HA tc_s9896.Lam Minor.S9896.HA = true := by decide +kernel
theorem eB : scaledEq Minor.S9896.HBd tc_s9896.HB tc_s9896.Lam Minor.S9896.HB = true := by decide +kernel
theorem eC : scaledEq Minor.S9896.HCd tc_s9896.HC tc_s9896.Lam Minor.S9896.HC = true := by decide +kernel

/-- **Slab S9896.** -/
theorem spec : ThomsonGen.SlabSpec phi2 (-49 / 50 : ℝ) (-24 / 25 : ℝ) :=
  slabSpec_of_minor tc_s9896 tc_s9896_meta tc_s9896_A tc_s9896_B tc_s9896_G alo_eq ahi_eq ef_gt lam_pos
    (by decide) (by decide) (by decide) eA eB eC
    (fun t h1 h2 => Minor.S9896.HA_le h1 h2) (fun t h1 h2 => Minor.S9896.HB_le h1 h2)
    (fun t h1 h2 => Minor.S9896.HC_le h1 h2)

end S9896
end Riesz2
