import Riesz2.S9694.Data
/-! Kernel check `chkA` of the slab S9694.
    Generated by `lean/gen_riesz2/emit_tcert.py` from `cert_slab_96_94_riesz2.json` (sha256 34db5c11416c7f7d…).
    Riesz s = 2 kernel `phi2 t = 1/(2-2t)`; format = upstream `TCert` (ThomsonGen/CertT.lean).
    Regenerate; do not edit. -/

open Real

section Riesz2_S9694_tc
namespace Riesz2
open ThomsonN7 ThomsonN7.Kron ThomsonN7.Kron.Ex ThomsonN7.Cert ThomsonN7.ThreePoint

theorem tc_s9694_A : tc_s9694.chkA = true := by decide +kernel

end Riesz2
end Riesz2_S9694_tc
