import Riesz2.S9694.ChkMeta
import Riesz2.S9694.ChkA
import Riesz2.S9694.ChkB
import Riesz2.S9694.ChkG
import Riesz2.Bridge
import Riesz2.MinorS9694
/-! Slab S9694: `ThomsonGen.SlabSpec phi2 -24/25 -47/50` from the checked packed certificate `tc_s9694`
and the 1-D minorants of `Riesz2.Minor.S9694` (identified through `scaledEq`).
Generated by lean/gen_riesz2/gen_spec2.py; do not edit. -/

open Real
namespace Riesz2
namespace S9694
open Minor ThomsonN7.Cert

theorem e_eq : tc_s9694.e = 189080971429930270720 := rfl
theorem lam_eq : tc_s9694.Lam = 18446744073709551616 := rfl
theorem an_eq : tc_s9694.an = -24 := rfl
theorem ad_eq : tc_s9694.ad = 25 := rfl
theorem bn_eq : tc_s9694.bn = -47 := rfl
theorem bd_eq : tc_s9694.bd = 50 := rfl
theorem lam_pos : 0 < tc_s9694.Lam := by rw [lam_eq]; norm_num
theorem alo_eq : tc_s9694.alo = (-24 / 25 : ℝ) := by
  unfold TCert.alo; rw [an_eq, ad_eq]; norm_num
theorem ahi_eq : tc_s9694.ahi = (-47 / 50 : ℝ) := by
  unfold TCert.ahi; rw [bn_eq, bd_eq]; norm_num
theorem ef_gt : (41 / 4 : ℝ) < tc_s9694.ef := by
  unfold TCert.ef; rw [e_eq, lam_eq]; norm_num
theorem eA : scaledEq Minor.S9694.HAd tc_s9694.HA tc_s9694.Lam Minor.S9694.HA = true := by decide +kernel
theorem eB : scaledEq Minor.S9694.HBd tc_s9694.HB tc_s9694.Lam Minor.S9694.HB = true := by decide +kernel
theorem eC : scaledEq Minor.S9694.HCd tc_s9694.HC tc_s9694.Lam Minor.S9694.HC = true := by decide +kernel

/-- **Slab S9694.** -/
theorem spec : ThomsonGen.SlabSpec phi2 (-24 / 25 : ℝ) (-47 / 50 : ℝ) :=
  slabSpec_of_minor tc_s9694 tc_s9694_meta tc_s9694_A tc_s9694_B tc_s9694_G alo_eq ahi_eq ef_gt lam_pos
    (by decide) (by decide) (by decide) eA eB eC
    (fun t h1 h2 => Minor.S9694.HA_le h1 h2) (fun t h1 h2 => Minor.S9694.HB_le h1 h2)
    (fun t h1 h2 => Minor.S9694.HC_le h1 h2)

end S9694
end Riesz2
