import CoulN7.S9998.Data
import ThomsonGen.Cert.Split
/-! Kernel check `checkMeta` of `tc_s9998`, one `decide` per block.
    Generated by `numerics/n7_interval/lean/gen/gen_split.py`; do not edit. -/

open Real

section CoulN7_S9998_split
namespace CoulN7
open ThomsonN7 ThomsonN7.Kron ThomsonN7.Kron.Ex ThomsonN7.Cert ThomsonN7.ThreePoint

set_option maxHeartbeats 0

theorem tc_s9998_mP0 : (tc_s9998.blkP 0).ok (tc_s9998.m 0) = true := by decide +kernel
theorem tc_s9998_mP1 : (tc_s9998.blkP 1).ok (tc_s9998.m 1) = true := by decide +kernel
theorem tc_s9998_mP2 : (tc_s9998.blkP 2).ok (tc_s9998.m 2) = true := by decide +kernel
theorem tc_s9998_mP3 : (tc_s9998.blkP 3).ok (tc_s9998.m 3) = true := by decide +kernel
theorem tc_s9998_mP4 : (tc_s9998.blkP 4).ok (tc_s9998.m 4) = true := by decide +kernel
theorem tc_s9998_mP5 : (tc_s9998.blkP 5).ok (tc_s9998.m 5) = true := by decide +kernel
theorem tc_s9998_mP : (List.range tc_s9998.K).all (fun k => (tc_s9998.blkP k).ok (tc_s9998.m k)) = true := by
  rw [show tc_s9998.K = 6 from rfl, show List.range 6 = [0, 1, 2, 3, 4, 5] from rfl]
  simp only [List.all_cons, List.all_nil, tc_s9998_mP0, tc_s9998_mP1, tc_s9998_mP2, tc_s9998_mP3, tc_s9998_mP4, tc_s9998_mP5, Bool.and_true, Bool.true_and, Bool.and_self]

theorem tc_s9998_mR0 : (tc_s9998.blkR 0).ok (tc_s9998.m 0) = true := by decide +kernel
theorem tc_s9998_mR1 : (tc_s9998.blkR 1).ok (tc_s9998.m 1) = true := by decide +kernel
theorem tc_s9998_mR2 : (tc_s9998.blkR 2).ok (tc_s9998.m 2) = true := by decide +kernel
theorem tc_s9998_mR3 : (tc_s9998.blkR 3).ok (tc_s9998.m 3) = true := by decide +kernel
theorem tc_s9998_mR4 : (tc_s9998.blkR 4).ok (tc_s9998.m 4) = true := by decide +kernel
theorem tc_s9998_mR5 : (tc_s9998.blkR 5).ok (tc_s9998.m 5) = true := by decide +kernel
theorem tc_s9998_mR : (List.range tc_s9998.K).all (fun k => (tc_s9998.blkR k).ok (tc_s9998.m k)) = true := by
  rw [show tc_s9998.K = 6 from rfl, show List.range 6 = [0, 1, 2, 3, 4, 5] from rfl]
  simp only [List.all_cons, List.all_nil, tc_s9998_mR0, tc_s9998_mR1, tc_s9998_mR2, tc_s9998_mR3, tc_s9998_mR4, tc_s9998_mR5, Bool.and_true, Bool.true_and, Bool.and_self]

theorem tc_s9998_mSA0 : okF (tc_s9998_SA0).z.length (tc_s9998_SA0).B = true := by decide +kernel
theorem tc_s9998_mSA1 : okF (tc_s9998_SA1).z.length (tc_s9998_SA1).B = true := by decide +kernel
theorem tc_s9998_mSA2 : okF (tc_s9998_SA2).z.length (tc_s9998_SA2).B = true := by decide +kernel
theorem tc_s9998_mSA3 : okF (tc_s9998_SA3).z.length (tc_s9998_SA3).B = true := by decide +kernel
theorem tc_s9998_mSA4 : okF (tc_s9998_SA4).z.length (tc_s9998_SA4).B = true := by decide +kernel
theorem tc_s9998_mSA5 : okF (tc_s9998_SA5).z.length (tc_s9998_SA5).B = true := by decide +kernel
theorem tc_s9998_mSA6 : okF (tc_s9998_SA6).z.length (tc_s9998_SA6).B = true := by decide +kernel
theorem tc_s9998_mSA7 : okF (tc_s9998_SA7).z.length (tc_s9998_SA7).B = true := by decide +kernel
theorem tc_s9998_mSA8 : okF (tc_s9998_SA8).z.length (tc_s9998_SA8).B = true := by decide +kernel
theorem tc_s9998_mSA : tc_s9998.SA.all (fun s => okF s.z.length s.B) = true := by
  rw [show tc_s9998.SA = [tc_s9998_SA0, tc_s9998_SA1, tc_s9998_SA2, tc_s9998_SA3, tc_s9998_SA4, tc_s9998_SA5, tc_s9998_SA6, tc_s9998_SA7, tc_s9998_SA8] from rfl]
  simp only [List.all_cons, List.all_nil, tc_s9998_mSA0, tc_s9998_mSA1, tc_s9998_mSA2, tc_s9998_mSA3, tc_s9998_mSA4, tc_s9998_mSA5, tc_s9998_mSA6, tc_s9998_mSA7, tc_s9998_mSA8, Bool.and_true, Bool.true_and, Bool.and_self]

theorem tc_s9998_mSB0 : okF (tc_s9998_SB0).z.length (tc_s9998_SB0).B = true := by decide +kernel
theorem tc_s9998_mSB1 : okF (tc_s9998_SB1).z.length (tc_s9998_SB1).B = true := by decide +kernel
theorem tc_s9998_mSB2 : okF (tc_s9998_SB2).z.length (tc_s9998_SB2).B = true := by decide +kernel
theorem tc_s9998_mSB3 : okF (tc_s9998_SB3).z.length (tc_s9998_SB3).B = true := by decide +kernel
theorem tc_s9998_mSB4 : okF (tc_s9998_SB4).z.length (tc_s9998_SB4).B = true := by decide +kernel
theorem tc_s9998_mSB5 : okF (tc_s9998_SB5).z.length (tc_s9998_SB5).B = true := by decide +kernel
theorem tc_s9998_mSB6 : okF (tc_s9998_SB6).z.length (tc_s9998_SB6).B = true := by decide +kernel
theorem tc_s9998_mSB7 : okF (tc_s9998_SB7).z.length (tc_s9998_SB7).B = true := by decide +kernel
theorem tc_s9998_mSB : tc_s9998.SB.all (fun s => okF s.z.length s.B) = true := by
  rw [show tc_s9998.SB = [tc_s9998_SB0, tc_s9998_SB1, tc_s9998_SB2, tc_s9998_SB3, tc_s9998_SB4, tc_s9998_SB5, tc_s9998_SB6, tc_s9998_SB7] from rfl]
  simp only [List.all_cons, List.all_nil, tc_s9998_mSB0, tc_s9998_mSB1, tc_s9998_mSB2, tc_s9998_mSB3, tc_s9998_mSB4, tc_s9998_mSB5, tc_s9998_mSB6, tc_s9998_mSB7, Bool.and_true, Bool.true_and, Bool.and_self]

theorem tc_s9998_mSG0 : okF (tc_s9998_SG0).z.length (tc_s9998_SG0).B = true := by decide +kernel
theorem tc_s9998_mSG1 : okF (tc_s9998_SG1).z.length (tc_s9998_SG1).B = true := by decide +kernel
theorem tc_s9998_mSG2 : okF (tc_s9998_SG2).z.length (tc_s9998_SG2).B = true := by decide +kernel
theorem tc_s9998_mSG3 : okF (tc_s9998_SG3).z.length (tc_s9998_SG3).B = true := by decide +kernel
theorem tc_s9998_mSG4 : okF (tc_s9998_SG4).z.length (tc_s9998_SG4).B = true := by decide +kernel
theorem tc_s9998_mSG5 : okF (tc_s9998_SG5).z.length (tc_s9998_SG5).B = true := by decide +kernel
theorem tc_s9998_mSG6 : okF (tc_s9998_SG6).z.length (tc_s9998_SG6).B = true := by decide +kernel
theorem tc_s9998_mSG7 : okF (tc_s9998_SG7).z.length (tc_s9998_SG7).B = true := by decide +kernel
theorem tc_s9998_mSG : tc_s9998.SG.all (fun s => okF s.z.length s.B) = true := by
  rw [show tc_s9998.SG = [tc_s9998_SG0, tc_s9998_SG1, tc_s9998_SG2, tc_s9998_SG3, tc_s9998_SG4, tc_s9998_SG5, tc_s9998_SG6, tc_s9998_SG7] from rfl]
  simp only [List.all_cons, List.all_nil, tc_s9998_mSG0, tc_s9998_mSG1, tc_s9998_mSG2, tc_s9998_mSG3, tc_s9998_mSG4, tc_s9998_mSG5, tc_s9998_mSG6, tc_s9998_mSG7, Bool.and_true, Bool.true_and, Bool.and_self]

theorem tc_s9998_meta : tc_s9998.checkMeta = true :=
  TCert.checkMeta_of_parts tc_s9998 (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel)
    tc_s9998_mP tc_s9998_mR tc_s9998_mSA tc_s9998_mSB tc_s9998_mSG
end CoulN7
end CoulN7_S9998_split
