import CoulN7.S9998.ChkMeta
import CoulN7.S9998.ChkA
import CoulN7.S9998.ChkB
import CoulN7.S9998.ChkG
import CoulN7.Bridge
import CoulN7.Minor.S9998
/-! Slab S9998: `ThomsonGen.SlabSpec φ₁ (-99 / 100 : ℝ) (-49 / 50 : ℝ)` (Coulomb) from the checked packed certificate `tc_s9998` and
the minorants of `CoulN7.Minor.MS9998` (identified through `scaledEq`).
Generated by `numerics/n7_interval/lean/gen/gen_spec1.py`; do not edit. -/

open Real
namespace CoulN7
namespace S9998
open ThomsonN7 ThomsonN7.Cert ThomsonGen

theorem e_eq : tc_s9998.e = 266610559930686275584 := rfl
theorem lam_eq : tc_s9998.Lam = 18446744073709551616 := rfl
theorem an_eq : tc_s9998.an = -99 := rfl
theorem ad_eq : tc_s9998.ad = 100 := rfl
theorem bn_eq : tc_s9998.bn = -49 := rfl
theorem bd_eq : tc_s9998.bd = 50 := rfl
theorem lam_pos : 0 < tc_s9998.Lam := by rw [lam_eq]; norm_num
theorem alo_eq : tc_s9998.alo = (-99 / 100 : ℝ) := by
  unfold TCert.alo; rw [an_eq, ad_eq]; norm_num
theorem ahi_eq : tc_s9998.ahi = (-49 / 50 : ℝ) := by
  unfold TCert.ahi; rw [bn_eq, bd_eq]; norm_num
/-- `E(P) < ef` (margin 1.000e-05). -/
theorem ef_gt : pairEnergy ThomsonN7.Base.phi pentBipyramid < tc_s9998.ef := by
  refine lt_of_le_of_lt pairEnergy_pent_le ?_
  unfold TCert.ef; rw [e_eq, lam_eq]; norm_num
theorem eA : scaledEq CoulN7.Minor.MS9998.HAd tc_s9998.HA tc_s9998.Lam CoulN7.Minor.MS9998.HA = true := by decide +kernel
theorem eB : scaledEq CoulN7.Minor.MS9998.HBd tc_s9998.HB tc_s9998.Lam CoulN7.Minor.MS9998.HB = true := by decide +kernel
theorem eC : scaledEq CoulN7.Minor.MS9998.HCd tc_s9998.HC tc_s9998.Lam CoulN7.Minor.MS9998.HC = true := by decide +kernel

/-- **Slab S9998.** -/
theorem spec : SlabSpec ThomsonN7.Base.phi (-99 / 100 : ℝ) (-49 / 50 : ℝ) :=
  slabSpec_of_minor tc_s9998 tc_s9998_meta tc_s9998_A tc_s9998_B tc_s9998_G alo_eq ahi_eq ef_gt lam_pos
    (by decide) (by decide) (by decide) eA eB eC
    (fun t h1 h2 => CoulN7.Minor.MS9998.HA_le t h1 h2) (fun t h1 h2 => CoulN7.Minor.MS9998.HB_le t h1 h2)
    (fun t h1 h2 => CoulN7.Minor.MS9998.HC_le t h1 h2)

end S9998
end CoulN7
