import Riesz2.S9493.Data
/-! Kernel check `checkMeta` of the slab S9493.
    Generated by `lean/gen_riesz2/emit_tcert.py` from `cert_slab_94_93_riesz2.json` (sha256 02a3f286ccd937cd…).
    Riesz s = 2 kernel `phi2 t = 1/(2-2t)`; format = upstream `TCert` (ThomsonGen/CertT.lean).
    Regenerate; do not edit. -/

open Real

section Riesz2_S9493_tc
namespace Riesz2
open ThomsonN7 ThomsonN7.Kron ThomsonN7.Kron.Ex ThomsonN7.Cert ThomsonN7.ThreePoint

theorem tc_s9493_meta : tc_s9493.checkMeta = true := by decide +kernel

end Riesz2
end Riesz2_S9493_tc
