import Riesz2.S9493.ChkMeta
import Riesz2.S9493.ChkA
import Riesz2.S9493.ChkB
import Riesz2.S9493.ChkG
import Riesz2.Bridge
import Riesz2.MinorS9493
/-! Slab S9493: `ThomsonGen.SlabSpec phi2 -47/50 -93/100` from the checked packed certificate `tc_s9493`
and the 1-D minorants of `Riesz2.Minor.S9493` (identified through `scaledEq`).
Generated by lean/gen_riesz2/gen_spec2.py; do not edit. -/

open Real
namespace Riesz2
namespace S9493
open Minor ThomsonN7.Cert

theorem e_eq : tc_s9493.e = 189080971429930598400 := rfl
theorem lam_eq : tc_s9493.Lam = 18446744073709551616 := rfl
theorem an_eq : tc_s9493.an = -47 := rfl
theorem ad_eq : tc_s9493.ad = 50 := rfl
theorem bn_eq : tc_s9493.bn = -93 := rfl
theorem bd_eq : tc_s9493.bd = 100 := rfl
theorem lam_pos : 0 < tc_s9493.Lam := by rw [lam_eq]; norm_num
theorem alo_eq : tc_s9493.alo = (-47 / 50 : ℝ) := by
  unfold TCert.alo; rw [an_eq, ad_eq]; norm_num
theorem ahi_eq : tc_s9493.ahi = (-93 / 100 : ℝ) := by
  unfold TCert.ahi; rw [bn_eq, bd_eq]; norm_num
theorem ef_gt : (41 / 4 : ℝ) < tc_s9493.ef := by
  unfold TCert.ef; rw [e_eq, lam_eq]; norm_num
theorem eA : scaledEq Minor.S9493.HAd tc_s9493.HA tc_s9493.Lam Minor.S9493.HA = true := by decide +kernel
theorem eB : scaledEq Minor.S9493.HBd tc_s9493.HB tc_s9493.Lam Minor.S9493.HB = true := by decide +kernel
theorem eC : scaledEq Minor.S9493.HCd tc_s9493.HC tc_s9493.Lam Minor.S9493.HC = true := by decide +kernel

/-- **Slab S9493.** -/
theorem spec : ThomsonGen.SlabSpec phi2 (-47 / 50 : ℝ) (-93 / 100 : ℝ) :=
  slabSpec_of_minor tc_s9493 tc_s9493_meta tc_s9493_A tc_s9493_B tc_s9493_G alo_eq ahi_eq ef_gt lam_pos
    (by decide) (by decide) (by decide) eA eB eC
    (fun t h1 h2 => Minor.S9493.HA_le h1 h2) (fun t h1 h2 => Minor.S9493.HB_le h1 h2)
    (fun t h1 h2 => Minor.S9493.HC_le h1 h2)

end S9493
end Riesz2
