import LogLean.LocalFrames
import LogLean.LocalPairData

/-!
# LocalPairsC: pair-level Taylor-link identities `T6_g(atoms_ij(x)) = p_ij(x)` (T1), pairs [(2, 6), (3, 4), (3, 5), (3, 6), (4, 5), (4, 6), (5, 6)]

GENERATED by `lean/gen/export_local_data.py pairs`; each identity is one `decide +kernel`
(`LocalSP.checkEq6`), turned into the real identity by `LocalSP.eq_of_checkEq6` in `LocalMain`.
-/

namespace LocalPairs
open LocalKel LocalSP LocalAtom LocalFrames LocalPairData

set_option profiler true in
theorem check26 : checkEq6 (T6of 2 6) (atA 2 6) (atB 2 6) (atC 2 6) (atCp 2 6) atRi atRj (pij 2 6) = true := by
  decide +kernel

set_option profiler true in
theorem check34 : checkEq6 (T6of 3 4) (atA 3 4) (atB 3 4) (atC 3 4) (atCp 3 4) atRi atRj (pij 3 4) = true := by
  decide +kernel

set_option profiler true in
theorem check35 : checkEq6 (T6of 3 5) (atA 3 5) (atB 3 5) (atC 3 5) (atCp 3 5) atRi atRj (pij 3 5) = true := by
  decide +kernel

set_option profiler true in
theorem check36 : checkEq6 (T6of 3 6) (atA 3 6) (atB 3 6) (atC 3 6) (atCp 3 6) atRi atRj (pij 3 6) = true := by
  decide +kernel

set_option profiler true in
theorem check45 : checkEq6 (T6of 4 5) (atA 4 5) (atB 4 5) (atC 4 5) (atCp 4 5) atRi atRj (pij 4 5) = true := by
  decide +kernel

set_option profiler true in
theorem check46 : checkEq6 (T6of 4 6) (atA 4 6) (atB 4 6) (atC 4 6) (atCp 4 6) atRi atRj (pij 4 6) = true := by
  decide +kernel

set_option profiler true in
theorem check56 : checkEq6 (T6of 5 6) (atA 5 6) (atB 5 6) (atC 5 6) (atCp 5 6) atRi atRj (pij 5 6) = true := by
  decide +kernel

end LocalPairs

#print axioms LocalPairs.check26
#print axioms LocalPairs.check34
#print axioms LocalPairs.check35
#print axioms LocalPairs.check36
#print axioms LocalPairs.check45
#print axioms LocalPairs.check46
#print axioms LocalPairs.check56
