import LogLean.LocalGlobD3a
import LogLean.LocalGlobD3b
import LogLean.LocalGlobD3c
import LogLean.LocalGlobD3d
import LogLean.LocalGlobD3e
import LogLean.LocalGlobD3f
import LogLean.LocalGlobD3g

/-! # LocalGlobD4: the quartic multinomial list `S4m = P0 + … + P6`, `wsub` and `Sok` on it (GENERATED by `lean/gen/split_d2.py`; consequences in LocalGlobal) -/

namespace LocalGlobal
open LocalKel LocalSP LocalBomb LocalGlobData

/-- balanced merge tree (≈ 16k monomial comparisons instead of ≈ 27k for the linear chain) -/
def S4m : Poly := merge (merge (merge P0 P1) (merge P2 P3)) (merge (merge P4 P5) P6)

theorem chunks_eq : sumsq 16 2 14 = (((sumsq 16 2 14).drop 0).take 2) ++ (((sumsq 16 2 14).drop 2).take 2) ++ (((sumsq 16 2 14).drop 4).take 2) ++ (((sumsq 16 2 14).drop 6).take 2) ++ (((sumsq 16 2 14).drop 8).take 2) ++ (((sumsq 16 2 14).drop 10).take 2) ++ (((sumsq 16 2 14).drop 12).take 2) := by decide +kernel

set_option profiler true in
theorem ws4 : wsub 4 (constDP G4_0) S4m = true := by decide +kernel
set_option profiler true in
theorem Sok4m : Sok S4m = true := by decide +kernel

end LocalGlobal
