import LogLean.LocalAtom

/-!
# LocalFrames: the bipyramid, its frames and the pair classes over K = ℚ(α) (generated data)

GENERATED by `lean/gen/export_local_data.py frames` from `local_global.py`; do not edit.
`Pk i k`, `E1k i k`, `E2k i k`: coordinates of `Pᵢ` and of the tangent frame `(E1ᵢ, E2ᵢ)` (ring: `e_z`,
`(−sin θ, cos θ, 0)`; poles: `e_x`, `e_y`); `Kd p b`: the five kernel vectors (rotation fields `b = 0,1,2`, `ŝ₁ ŝ₂`).
`clsIdx i j` selects the class data of `LocalAtom` (0 adj, 1 diag, 2 pole–ring, 3 pole–pole); `atA … atRj` are the
six pair atoms as polynomials in the 4 local coordinates `(x_{2i}, x_{2i+1}, x_{2j}, x_{2j+1})`.
The Boolean checks (`frameOK`, `rotOK`, `gramOK`, `pairOK`, `critOK`, `symOK`, `clsOK`) are the exact K-identities
that `LocalGeom` needs; each is proved by `decide +kernel`.
-/

namespace LocalFrames
open LocalKel LocalSP LocalAtom

def Pdat : List (List Kel) :=
  [[⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
   [⟨-3/2, 0, 1/8, 0⟩, ⟨0, 1/4, 0, 0⟩, ⟨0, 0, 0, 0⟩],
   [⟨1, 0, -1/8, 0⟩, ⟨0, -3/4, 0, 1/16⟩, ⟨0, 0, 0, 0⟩],
   [⟨1, 0, -1/8, 0⟩, ⟨0, 3/4, 0, -1/16⟩, ⟨0, 0, 0, 0⟩],
   [⟨-3/2, 0, 1/8, 0⟩, ⟨0, -1/4, 0, 0⟩, ⟨0, 0, 0, 0⟩],
   [⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩],
   [⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨-1, 0, 0, 0⟩]]
def E1dat : List (List Kel) :=
  [[⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩],
   [⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩],
   [⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩],
   [⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩],
   [⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩],
   [⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
   [⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩]]
def E2dat : List (List Kel) :=
  [[⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
   [⟨0, -1/4, 0, 0⟩, ⟨-3/2, 0, 1/8, 0⟩, ⟨0, 0, 0, 0⟩],
   [⟨0, 3/4, 0, -1/16⟩, ⟨1, 0, -1/8, 0⟩, ⟨0, 0, 0, 0⟩],
   [⟨0, -3/4, 0, 1/16⟩, ⟨1, 0, -1/8, 0⟩, ⟨0, 0, 0, 0⟩],
   [⟨0, 1/4, 0, 0⟩, ⟨-3/2, 0, 1/8, 0⟩, ⟨0, 0, 0, 0⟩],
   [⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
   [⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩]]
/-- kernel vectors: row `p` = coordinate `p`, columns `r₁ r₂ r₃ ŝ₁ ŝ₂` -/
def Kdat : List (List Kel) :=
  [[⟨0, 0, 0, 0⟩, ⟨-1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
   [⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
   [⟨0, 1/4, 0, 0⟩, ⟨3/2, 0, -1/8, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, -1/8, 0⟩, ⟨0, -3/4, 0, 1/16⟩],
   [⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
   [⟨0, -3/4, 0, 1/16⟩, ⟨-1, 0, 1/8, 0⟩, ⟨0, 0, 0, 0⟩, ⟨-3/2, 0, 1/8, 0⟩, ⟨0, -1/4, 0, 0⟩],
   [⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
   [⟨0, 3/4, 0, -1/16⟩, ⟨-1, 0, 1/8, 0⟩, ⟨0, 0, 0, 0⟩, ⟨-3/2, 0, 1/8, 0⟩, ⟨0, 1/4, 0, 0⟩],
   [⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
   [⟨0, -1/4, 0, 0⟩, ⟨3/2, 0, -1/8, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, -1/8, 0⟩, ⟨0, 3/4, 0, -1/16⟩],
   [⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
   [⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
   [⟨-1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
   [⟨0, 0, 0, 0⟩, ⟨-1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
   [⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩]]
def clsTab : List (List ℕ) := [[4, 0, 1, 1, 0, 2, 2], [0, 4, 0, 1, 1, 2, 2], [1, 0, 4, 0, 1, 2, 2], [1, 1, 0, 4, 0, 2, 2], [0, 1, 1, 0, 4, 2, 2], [2, 2, 2, 2, 2, 4, 3], [2, 2, 2, 2, 2, 3, 4]]

def Pk (i k : ℕ) : Kel := (Pdat.getD i []).getD k Kel.zero
def E1k (i k : ℕ) : Kel := (E1dat.getD i []).getD k Kel.zero
def E2k (i k : ℕ) : Kel := (E2dat.getD i []).getD k Kel.zero
def Kd (p b : ℕ) : Kel := (Kdat.getD p []).getD b Kel.zero
/-- Gram diagonal of the kernel vectors -/
def gram (b : ℕ) : ℚ := [9/2, 9/2, 5, 5/2, 5/2].getD b 0

/-- class of the pair: 0 adj, 1 diag, 2 pole–ring, 3 pole–pole (4 on the diagonal) -/
def clsIdx (i j : ℕ) : ℕ := (clsTab.getD i []).getD j 4
def gof (i j : ℕ) : Kel := match clsIdx i j with | 0 => g_adj | 1 => g_diag | 2 => g_pole | _ => g_pp
def Wof (i j : ℕ) : Kel := match clsIdx i j with | 0 => W_adj | 1 => W_diag | 2 => W_pole | _ => W_pp
def invof (i j : ℕ) : Kel := match clsIdx i j with | 0 => inv_adj | 1 => inv_diag | 2 => inv_pole | _ => inv_pp
def T6of (i j : ℕ) : T6 := match clsIdx i j with | 0 => T6adj | 1 => T6diag | 2 => T6pole | _ => T6pp
def Kof (i j : ℕ) : ℚ := match clsIdx i j with | 0 => K_adj | 1 => K_diag | 2 => K_pole | _ => K_pp
def clof (i j : ℕ) : Cls := match clsIdx i j with | 0 => cl_adj | 1 => cl_diag | 2 => cl_pole | _ => cl_pp
/-- `W_ij` with zero diagonal -/
def Wtab (i j : ℕ) : Kel := if i = j then Kel.zero else Wof i j
/-- `μᵢ`: 0 on the ring, −1/4 at the poles -/
def muk (i : ℕ) : Kel := if i < 5 then Kel.zero else Kel.ofQ (-1/4)

def dotK (u v : ℕ → Kel) : Kel := ((u 0).mul (v 0)).add (((u 1).mul (v 1)).add ((u 2).mul (v 2)))
/-- `e_c × P` -/
def crossK (c : ℕ) (P : ℕ → Kel) (k : ℕ) : Kel :=
  if c = 0 then (if k = 0 then Kel.zero else if k = 1 then Kel.zero.sub (P 2) else P 1)
  else if c = 1 then (if k = 0 then P 2 else if k = 1 then Kel.zero else Kel.zero.sub (P 0))
  else (if k = 0 then Kel.zero.sub (P 1) else if k = 1 then P 0 else Kel.zero)
def ksum (l : List Kel) : Kel := l.foldr Kel.add Kel.zero

/-! ### The six pair atoms as polynomials in `(x₁, x₂, x₃, x₄) = (x_{2i}, x_{2i+1}, x_{2j}, x_{2j+1})` -/

def atA (i j : ℕ) : Poly :=
  [([0, 0, 0, 1], dotK (Pk i) (E2k j)), ([0, 0, 1, 0], dotK (Pk i) (E1k j)),
   ([0, 1, 0, 0], dotK (E2k i) (Pk j)), ([1, 0, 0, 0], dotK (E1k i) (Pk j))]
def atB (i j : ℕ) : Poly :=
  [([0, 1, 0, 1], dotK (E2k i) (E2k j)), ([0, 1, 1, 0], dotK (E2k i) (E1k j)),
   ([1, 0, 0, 1], dotK (E1k i) (E2k j)), ([1, 0, 1, 0], dotK (E1k i) (E1k j))]
def atC (i j : ℕ) : Poly := [([0, 0, 0, 1], dotK (Pk i) (E2k j)), ([0, 0, 1, 0], dotK (Pk i) (E1k j))]
def atCp (i j : ℕ) : Poly := [([0, 1, 0, 0], dotK (E2k i) (Pk j)), ([1, 0, 0, 0], dotK (E1k i) (Pk j))]
def atRi : Poly := [([0, 2, 0, 0], Kel.ofQ 1), ([2, 0, 0, 0], Kel.ofQ 1)]
def atRj : Poly := [([0, 0, 0, 2], Kel.ofQ 1), ([0, 0, 2, 0], Kel.ofQ 1)]

/-! ### Exact K-identities (each one `decide +kernel`) -/

/-- orthonormal frames and completeness -/
def frameOK : Bool := (List.range 7).all fun i =>
  decide (dotK (Pk i) (Pk i) = Kel.ofQ 1) && decide (dotK (E1k i) (E1k i) = Kel.ofQ 1)
  && decide (dotK (E2k i) (E2k i) = Kel.ofQ 1) && decide (dotK (Pk i) (E1k i) = Kel.zero)
  && decide (dotK (Pk i) (E2k i) = Kel.zero) && decide (dotK (E1k i) (E2k i) = Kel.zero)
  && ((List.range 3).all fun k => (List.range 3).all fun l =>
      decide (((Pk i k).mul (Pk i l)).add (((E1k i k).mul (E1k i l)).add ((E2k i k).mul (E2k i l)))
        = Kel.ofQ (if k = l then 1 else 0)))
theorem frameOK_true : frameOK = true := by decide +kernel

/-- the rotation fields reconstruct `e_c × Pᵢ` -/
def rotOK : Bool := (List.range 7).all fun i => (List.range 3).all fun c => (List.range 3).all fun k =>
  decide (((Kd (2 * i) c).mul (E1k i k)).add ((Kd (2 * i + 1) c).mul (E2k i k)) = crossK c (Pk i) k)
theorem rotOK_true : rotOK = true := by decide +kernel

/-- Gram matrix of the kernel vectors -/
def gramOK : Bool := (List.range 5).all fun b => (List.range 5).all fun b' =>
  decide (ksum ((List.range 14).map fun p => (Kd p b).mul (Kd p b')) = Kel.ofQ (if b = b' then gram b else 0))
theorem gramOK_true : gramOK = true := by decide +kernel

/-- per pair: `⟪Pᵢ,Pⱼ⟫ = g`, `inv(1−g) = 1`, `2W = inv`, `g ≤ 0.31`, `1 − g² ≤ sg²`, `sg ≥ 0` -/
def pairOK : Bool := (List.range 7).all fun i => (List.range 7).all fun j =>
  if i = j then true else
  decide (dotK (Pk i) (Pk j) = gof i j) && decide ((invof i j).mul ((Kel.ofQ 1).sub (gof i j)) = Kel.ofQ 1)
  && decide ((Kel.ofQ 2).mul (Wof i j) = invof i j) && decide ((gof i j).hi aLo aHi ≤ 31/100)
  && (decide (((Kel.ofQ 1).sub ((gof i j).mul (gof i j))).hi aLo aHi ≤ (clof i j).bC ^ 2)
      && decide (0 ≤ (clof i j).bC))
theorem pairOK_true : pairOK = true := by decide +kernel

/-- criticality `Σ_{j≠i} W_ij Pⱼ = μᵢ Pᵢ` -/
def critOK : Bool := (List.range 7).all fun i => (List.range 3).all fun k =>
  decide (ksum ((List.range 7).map fun j => (Wtab i j).mul (Pk j k)) = (muk i).mul (Pk i k))
theorem critOK_true : critOK = true := by decide +kernel

def symOK : Bool := (List.range 7).all fun i => (List.range 7).all fun j => decide (Wtab i j = Wtab j i)
theorem symOK_true : symOK = true := by decide +kernel

def clsOK : Bool := (List.range 7).all fun i => (List.range 7).all fun j =>
  decide (clsIdx i j ≤ 4) && (decide (i = j) || decide (clsIdx i j < 4))
theorem clsOK_true : clsOK = true := by decide +kernel

lemma clsIdx_le {i j : ℕ} (hi : i < 7) (hj : j < 7) : clsIdx i j ≤ 4 := by
  have h := clsOK_true
  simp only [clsOK, List.all_eq_true, List.mem_range, Bool.and_eq_true, Bool.or_eq_true, decide_eq_true_eq] at h
  exact (h i hi j hj).1

lemma clsIdx_lt {i j : ℕ} (hi : i < 7) (hj : j < 7) (hij : i ≠ j) : clsIdx i j < 4 := by
  have h := clsOK_true
  simp only [clsOK, List.all_eq_true, List.mem_range, Bool.and_eq_true, Bool.or_eq_true, decide_eq_true_eq] at h
  exact (h i hi j hj).2.resolve_left hij

lemma Wtab_sym {i j : ℕ} (hi : i < 7) (hj : j < 7) : Wtab i j = Wtab j i := by
  have h := symOK_true
  simp only [symOK, List.all_eq_true, List.mem_range, decide_eq_true_eq] at h
  exact h i hi j hj

end LocalFrames
