import LogLean.LocalKel

/-! Attribution: adapted from huwngtran/thomson-n7-lean @ 25f2fa5, `ThomsonN7/Solution.lean` (ours ← upstream):
the block-sum step of `M_psd` follows `ThreePoint.dsum_pair12`. -/

/-!
# LocalCert: certificate (C′) of the quartic local lemma (`local/LOCAL_LEMMA.md` §3′)

GENERATED by `lean/gen/export_local_cert.py` from `lean/gen/LocalCert.template.lean`; do not edit the data block.

Statement proved (`Cprime`): for every `z ∈ ℝ¹⁴` orthogonal to the five kernel vectors
(rotation fields r₁ r₂ r₃ and the soft fields ŝ₁ ŝ₂, all with entries in K = ℚ(α)) and every `σ ∈ ℝ²`,

  ½⟨z,Hz⟩ + ⟨Γ m, z⟩ + (13/40)|s|⁴ ≥ (1/16)|z|² + (29/500)|s|⁴,
  m = (σ₁², σ₁σ₂, σ₂²),  |s|⁴ = (25/4)(σ₁²+σ₂²)²,

where `H` (14×14) and `Γ` (14×3) are the exported exact data over K (α = √(10+2√5) = 4 sin 72°).

Method (all exact, no floating point in the proof):
* elements of K are `Kel` = 4 rationals in the power basis of α, with α⁴ = 20α² − 80;
* the 17×17 matrix `M = [[½H − εI + KKᵀ, ½Γ], [½Γᵀ, c·G_θ]]` is *computed* from the data by `Kel`
  arithmetic (the penalty KKᵀ vanishes on W = ker(Kᵀ));
* `M = Lᵀ diag(D) L + E` with dyadic `L, D` (float LDLᵀ of M − 10⁻⁴·I, rounded), and `E` (entries in K)
  is shown diagonally dominant using rational enclosures of each entry on a rational box for α;
* the whole check is one `Bool` closed by `decide +kernel`.
`qform_dd_nonneg` and `list_sum_range_map` are copied from the upstream Coulomb proof
(huwngtran/thomson-n7-lean, `ThomsonN7/Solution.lean`, block CERT1).
-/

open Finset

namespace LocalCert
open LocalKel

/-! ## Data (generated) -/

/-- `H` (14×14 over K): Hessian of the minorant 𝒫 in the frame chart `t ∈ ℝ¹⁴` (F₂ = ½ tᵀHt). -/

def Hdat : List (List Kel) :=
  [[⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, -1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, -1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1/2, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨-1/2, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
  [⟨0, 0, 0, 0⟩, ⟨2, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, -1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨-1, 0, 1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨-1, 0, 1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, -1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1/2, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1/2, 0, 0, 0⟩],
  [⟨0, 0, 1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, -1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, -1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨-3/4, 0, 1/16, 0⟩, ⟨0, 1/8, 0, 0⟩, ⟨3/4, 0, -1/16, 0⟩, ⟨0, -1/8, 0, 0⟩],
  [⟨0, 0, 0, 0⟩, ⟨0, 0, -1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨2, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, -1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨-1, 0, 1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨-1, 0, 1/20, 0⟩, ⟨0, -1/8, 0, 0⟩, ⟨-3/4, 0, 1/16, 0⟩, ⟨0, -1/8, 0, 0⟩, ⟨-3/4, 0, 1/16, 0⟩],
  [⟨1, 0, -1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, -1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1/2, 0, -1/16, 0⟩, ⟨0, -3/8, 0, 1/32⟩, ⟨-1/2, 0, 1/16, 0⟩, ⟨0, 3/8, 0, -1/32⟩],
  [⟨0, 0, 0, 0⟩, ⟨-1, 0, 1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, -1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨2, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, -1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨-1, 0, 1/20, 0⟩, ⟨0, 3/8, 0, -1/32⟩, ⟨1/2, 0, -1/16, 0⟩, ⟨0, 3/8, 0, -1/32⟩, ⟨1/2, 0, -1/16, 0⟩],
  [⟨1, 0, -1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, -1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1/2, 0, -1/16, 0⟩, ⟨0, 3/8, 0, -1/32⟩, ⟨-1/2, 0, 1/16, 0⟩, ⟨0, -3/8, 0, 1/32⟩],
  [⟨0, 0, 0, 0⟩, ⟨-1, 0, 1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨-1, 0, 1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, -1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨2, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, -1/20, 0⟩, ⟨0, -3/8, 0, 1/32⟩, ⟨1/2, 0, -1/16, 0⟩, ⟨0, -3/8, 0, 1/32⟩, ⟨1/2, 0, -1/16, 0⟩],
  [⟨0, 0, 1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, -1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, -1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨-3/4, 0, 1/16, 0⟩, ⟨0, -1/8, 0, 0⟩, ⟨3/4, 0, -1/16, 0⟩, ⟨0, 1/8, 0, 0⟩],
  [⟨0, 0, 0, 0⟩, ⟨0, 0, -1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨-1, 0, 1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨-1, 0, 1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, -1/20, 0⟩, ⟨0, 0, 0, 0⟩, ⟨2, 0, 0, 0⟩, ⟨0, 1/8, 0, 0⟩, ⟨-3/4, 0, 1/16, 0⟩, ⟨0, 1/8, 0, 0⟩, ⟨-3/4, 0, 1/16, 0⟩],
  [⟨1/2, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨-3/4, 0, 1/16, 0⟩, ⟨0, -1/8, 0, 0⟩, ⟨1/2, 0, -1/16, 0⟩, ⟨0, 3/8, 0, -1/32⟩, ⟨1/2, 0, -1/16, 0⟩, ⟨0, -3/8, 0, 1/32⟩, ⟨-3/4, 0, 1/16, 0⟩, ⟨0, 1/8, 0, 0⟩, ⟨3/2, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1/4, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
  [⟨0, 0, 0, 0⟩, ⟨1/2, 0, 0, 0⟩, ⟨0, 1/8, 0, 0⟩, ⟨-3/4, 0, 1/16, 0⟩, ⟨0, -3/8, 0, 1/32⟩, ⟨1/2, 0, -1/16, 0⟩, ⟨0, 3/8, 0, -1/32⟩, ⟨1/2, 0, -1/16, 0⟩, ⟨0, -1/8, 0, 0⟩, ⟨-3/4, 0, 1/16, 0⟩, ⟨0, 0, 0, 0⟩, ⟨3/2, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1/4, 0, 0, 0⟩],
  [⟨-1/2, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨3/4, 0, -1/16, 0⟩, ⟨0, -1/8, 0, 0⟩, ⟨-1/2, 0, 1/16, 0⟩, ⟨0, 3/8, 0, -1/32⟩, ⟨-1/2, 0, 1/16, 0⟩, ⟨0, -3/8, 0, 1/32⟩, ⟨3/4, 0, -1/16, 0⟩, ⟨0, 1/8, 0, 0⟩, ⟨1/4, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨3/2, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
  [⟨0, 0, 0, 0⟩, ⟨1/2, 0, 0, 0⟩, ⟨0, -1/8, 0, 0⟩, ⟨-3/4, 0, 1/16, 0⟩, ⟨0, 3/8, 0, -1/32⟩, ⟨1/2, 0, -1/16, 0⟩, ⟨0, -3/8, 0, 1/32⟩, ⟨1/2, 0, -1/16, 0⟩, ⟨0, 1/8, 0, 0⟩, ⟨-3/4, 0, 1/16, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1/4, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨3/2, 0, 0, 0⟩]]

/-- `Γ` (14×3 over K): ∇F₃ at s = σ₁ŝ₁ + σ₂ŝ₂, columns for m = (σ₁², σ₁σ₂, σ₂²). -/

def Gdat : List (List Kel) :=
  [[⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
  [⟨0, 0, 0, 0⟩, ⟨2, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
  [⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
  [⟨0, 1/4, 0, 0⟩, ⟨-3, 0, 1/4, 0⟩, ⟨0, -1/4, 0, 0⟩],
  [⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
  [⟨0, -3/4, 0, 1/16⟩, ⟨2, 0, -1/4, 0⟩, ⟨0, 3/4, 0, -1/16⟩],
  [⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
  [⟨0, 3/4, 0, -1/16⟩, ⟨2, 0, -1/4, 0⟩, ⟨0, -3/4, 0, 1/16⟩],
  [⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
  [⟨0, -1/4, 0, 0⟩, ⟨-3, 0, 1/4, 0⟩, ⟨0, 1/4, 0, 0⟩],
  [⟨5/16, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨-5/16, 0, 0, 0⟩],
  [⟨0, 0, 0, 0⟩, ⟨-5/8, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
  [⟨5/16, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨-5/16, 0, 0, 0⟩],
  [⟨0, 0, 0, 0⟩, ⟨-5/8, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩]]

/-- Kernel vectors (14×5 over K): rotation fields r₁ r₂ r₃ and ŝ₁ ŝ₂; row `i` = coordinate `i`. -/

def Kdat : List (List Kel) :=
  [[⟨0, 0, 0, 0⟩, ⟨-1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
  [⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
  [⟨0, 1/4, 0, 0⟩, ⟨3/2, 0, -1/8, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, -1/8, 0⟩, ⟨0, -3/4, 0, 1/16⟩],
  [⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
  [⟨0, -3/4, 0, 1/16⟩, ⟨-1, 0, 1/8, 0⟩, ⟨0, 0, 0, 0⟩, ⟨-3/2, 0, 1/8, 0⟩, ⟨0, -1/4, 0, 0⟩],
  [⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
  [⟨0, 3/4, 0, -1/16⟩, ⟨-1, 0, 1/8, 0⟩, ⟨0, 0, 0, 0⟩, ⟨-3/2, 0, 1/8, 0⟩, ⟨0, 1/4, 0, 0⟩],
  [⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
  [⟨0, -1/4, 0, 0⟩, ⟨3/2, 0, -1/8, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, -1/8, 0⟩, ⟨0, 3/4, 0, -1/16⟩],
  [⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
  [⟨0, 0, 0, 0⟩, ⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
  [⟨-1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
  [⟨0, 0, 0, 0⟩, ⟨-1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩],
  [⟨1, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩, ⟨0, 0, 0, 0⟩]]

/-- LDLᵀ data (dyadic, 2^-40) of M − 1/10000·I: pivots. -/

def Ddat : List ℚ := [2679949641541/1099511627776, 2130193827653/1099511627776, 2671334394335/1099511627776, 1899046165663/1099511627776, 2609500473743/1099511627776, 814389260853/549755813888, 316620123969/137438953472, 46321598021/34359738368, 2502164148373/1099511627776, 368716390417/274877906944, 572832282503/549755813888, 572832282503/549755813888, 405629417449/549755813888, 405629417449/549755813888, 141675575/137438953472, 2064773939/549755813888, 28483869/68719476736]

/-- LDLᵀ data: row `q` is the column vector l_q (unit lower triangular L). -/

def Ldat : List (List ℚ) :=
  [[1, 0, -7792564303/137438953472, 0, -163209585637/1099511627776, 0, -163209585637/1099511627776, 0, -7792564303/137438953472, 0, -338325150091/1099511627776, 0, 338325150091/1099511627776, 0, 0, 0, 0],
  [0, 1, 0, 181094400677/549755813888, 0, 244544972107/549755813888, 0, 244544972107/549755813888, 0, 181094400677/549755813888, 0, 8867486933/68719476736, 0, 8867486933/68719476736, 0, 8867486933/17179869184, 0],
  [0, 0, 1, 0, -17956282023/274877906944, 0, -173019509377/1099511627776, 0, -167281953151/1099511627776, 0, -31032436305/274877906944, -80701014601/274877906944, 31032436305/274877906944, 80701014601/274877906944, 0, 0, 0],
  [0, 0, 0, 1, 0, 225553070335/1099511627776, 0, 367900337151/1099511627776, 0, 414790778909/1099511627776, -151359771981/1099511627776, -3245336499/1099511627776, -151359771981/1099511627776, -3245336499/1099511627776, 302719543961/1099511627776, -12981345997/1099511627776, -302719543961/1099511627776],
  [0, 0, 0, 0, 1, 0, -100474371673/1099511627776, 0, -188305886265/1099511627776, 0, 221223149009/1099511627776, -112908985875/549755813888, -221223149009/1099511627776, 112908985875/549755813888, 0, 0, 0],
  [0, 0, 0, 0, 0, 1, 0, 197577005/2147483648, 0, 329737941887/1099511627776, -36432857127/549755813888, -57970760873/274877906944, -36432857127/549755813888, -57970760873/274877906944, 36432857127/274877906944, -927532173969/1099511627776, -36432857127/274877906944],
  [0, 0, 0, 0, 0, 0, 1, 0, -30309494035/274877906944, 0, 118342946233/549755813888, 135572075381/1099511627776, -118342946233/549755813888, -135572075381/1099511627776, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 1, 0, 38910617195/549755813888, 192097586837/1099511627776, -28852261189/137438953472, 192097586837/1099511627776, -28852261189/137438953472, -192097586837/549755813888, -28852261189/34359738368, 192097586837/549755813888],
  [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, -86752173307/1099511627776, 266995735601/1099511627776, 86752173307/1099511627776, -266995735601/1099511627776, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 69720616755/274877906944, 90614406469/1099511627776, 69720616755/274877906944, 90614406469/1099511627776, -69720616755/137438953472, 362457625875/1099511627776, 69720616755/137438953472],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, -594029402241/1099511627776, 0, 129163661689/274877906944, 0, -129163661689/274877906944],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, -594029402241/1099511627776, 0, -129163661689/137438953472, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 561906792125/549755813888, 0, -561906792125/549755813888],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, -2247627168501/1099511627776, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, -850186355725/1099511627776],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]


/-! ## The certificate matrix and its check -/

def eps : ℚ := 1 / 16
def qp : ℚ := 29 / 500
def th : ℚ := -4999 / 5000
/-- `(13/40 − q′)·25/4`: the `|σ|⁴`-block scale (|s|⁴ = 25/4 |σ|⁴). -/
def cG : ℚ := (13 / 40 - qp) * (25 / 4)

def Hd (i j : ℕ) : Kel := (Hdat.getD i []).getD j Kel.zero
def Gd (i k : ℕ) : Kel := (Gdat.getD i []).getD k Kel.zero
def Kd (i b : ℕ) : Kel := (Kdat.getD i []).getD b Kel.zero
def Dd (q : ℕ) : ℚ := Ddat.getD q 0
def Ld (q i : ℕ) : ℚ := (Ldat.getD q []).getD i 0

/-- Gram matrix `G_θ` of `m = (σ₁², σ₁σ₂, σ₂²)`: `mᵀG_θm = (σ₁²+σ₂²)²` for every θ. -/
def Gth (k l : ℕ) : ℚ :=
  if k = 0 ∧ l = 0 then 1 else if k = 2 ∧ l = 2 then 1
  else if k = 1 ∧ l = 1 then 2 - 2 * th
  else if (k = 0 ∧ l = 2) ∨ (k = 2 ∧ l = 0) then th else 0

/-- Penalty `(KKᵀ)ᵢⱼ`. -/
def pen (i j : ℕ) : Kel :=
  ((((Kd i 0).mul (Kd j 0)).add ((Kd i 1).mul (Kd j 1))).add
    (((Kd i 2).mul (Kd j 2)).add ((Kd i 3).mul (Kd j 3)))).add ((Kd i 4).mul (Kd j 4))

def Mzz (i j : ℕ) : Kel :=
  (((Hd i j).smul (1 / 2)).sub (Kel.ofQ (if i = j then eps else 0))).add (pen i j)

/-- The 17×17 certificate matrix, computed from the data. -/
def Mk (i j : ℕ) : Kel :=
  if i < 14 then (if j < 14 then Mzz i j else (Gd i (j - 14)).smul (1 / 2))
  else (if j < 14 then (Gd j (i - 14)).smul (1 / 2) else Kel.ofQ (cG * Gth (i - 14) (j - 14)))

def ldl (i j : ℕ) : ℚ := ((List.range 17).map fun q => Dd q * Ld q i * Ld q j).sum

/-- Remainder `E = M − Lᵀ D L`, entrywise in K. -/
def Ek (i j : ℕ) : Kel := (Mk i j).sub (Kel.ofQ (ldl i j))

/-- The computable check: pivots ≥ 0, `E` symmetric, `E` diagonally dominant on the α-box. -/
def certOK : Bool :=
  (List.range 17).all fun i =>
    decide (0 ≤ Dd i) &&
    (List.range 17).all (fun j => decide (Ek i j = Ek j i)) &&
    decide (((List.range 17).map fun j => if i = j then (0 : ℚ) else (Ek i j).aub aLo aHi).sum
      ≤ (Ek i i).lo aLo aHi)

theorem certOK_true : certOK = true := by decide +kernel

lemma certOK_parts :
    (∀ i ∈ range 17, 0 ≤ Dd i) ∧ (∀ i ∈ range 17, ∀ j ∈ range 17, Ek i j = Ek j i) ∧
    (∀ i ∈ range 17, ∑ j ∈ range 17, (if i = j then (0 : ℚ) else (Ek i j).aub aLo aHi)
      ≤ (Ek i i).lo aLo aHi) := by
  have h := certOK_true
  simp only [certOK, List.all_eq_true, List.mem_range, Bool.and_eq_true, decide_eq_true_eq] at h
  refine ⟨fun i hi => (h i (mem_range.1 hi)).1.1, fun i hi j hj => ?_, fun i hi => ?_⟩
  · exact (h i (mem_range.1 hi)).1.2 j (mem_range.1 hj)
  · have := (h i (mem_range.1 hi)).2
    rwa [list_sum_range_map] at this

/-! ## Soundness: `M(a) ⪰ 0` for every real `a` in the box -/

theorem M_psd {a : ℝ} (hl : (aLo : ℝ) ≤ a) (hh : a ≤ aHi) (x : ℕ → ℝ) :
    0 ≤ ∑ i ∈ range 17, ∑ j ∈ range 17, x i * (Mk i j).ev a * x j := by
  obtain ⟨hD, hS, hDD⟩ := certOK_parts
  have hl0 : 0 ≤ (aLo : ℝ) := by norm_num [aLo]
  have hsplit : ∀ i j, (Mk i j).ev a = (∑ q ∈ range 17, (Dd q : ℝ) * Ld q i * Ld q j) + (Ek i j).ev a := by
    intro i j
    have e : ((ldl i j : ℚ) : ℝ) = ∑ q ∈ range 17, (Dd q : ℝ) * Ld q i * Ld q j := by
      unfold ldl; rw [list_sum_range_map]; push_cast; rfl
    rw [Ek, Kel.ev_sub, Kel.ev_ofQ, e]; ring
  have hsum : ∑ i ∈ range 17, ∑ j ∈ range 17, x i * (Mk i j).ev a * x j
      = ∑ q ∈ range 17, (Dd q : ℝ) * (∑ i ∈ range 17, (Ld q i : ℝ) * x i) ^ 2
        + ∑ i ∈ range 17, ∑ j ∈ range 17, x i * (Ek i j).ev a * x j := by
    have hA : ∀ i j, x i * (Mk i j).ev a * x j
        = ∑ q ∈ range 17, x i * ((Dd q : ℝ) * Ld q i * Ld q j) * x j + x i * (Ek i j).ev a * x j := by
      intro i j
      rw [hsplit, mul_add, add_mul, Finset.mul_sum, Finset.sum_mul]
    have e1 : ∀ q, (Dd q : ℝ) * (∑ i ∈ range 17, (Ld q i : ℝ) * x i) ^ 2
        = ∑ i ∈ range 17, ∑ j ∈ range 17, x i * ((Dd q : ℝ) * Ld q i * Ld q j) * x j := by
      intro q
      have hr := qf_rank1 (fun i => (Ld q i : ℝ)) x 17
      rw [← hr, Finset.mul_sum]
      refine Finset.sum_congr rfl fun i _ => ?_
      rw [Finset.mul_sum]
      refine Finset.sum_congr rfl fun j _ => ?_
      ring
    have hB : ∑ i ∈ range 17, ∑ j ∈ range 17, ∑ q ∈ range 17,
          x i * ((Dd q : ℝ) * Ld q i * Ld q j) * x j
        = ∑ q ∈ range 17, ∑ i ∈ range 17, ∑ j ∈ range 17,
          x i * ((Dd q : ℝ) * Ld q i * Ld q j) * x j := by
      calc _ = ∑ i ∈ range 17, ∑ q ∈ range 17, ∑ j ∈ range 17,
              x i * ((Dd q : ℝ) * Ld q i * Ld q j) * x j :=
            Finset.sum_congr rfl fun i _ => Finset.sum_comm
        _ = _ := Finset.sum_comm
    simp only [hA, Finset.sum_add_distrib, hB, e1]
  rw [hsum]
  refine add_nonneg (Finset.sum_nonneg fun q hq => mul_nonneg (by exact_mod_cast hD q hq) (sq_nonneg _)) ?_
  refine qform_dd_nonneg 17 (fun i j => (Ek i j).ev a) x
    (fun i hi j hj => by simp only [hS i hi j hj]) (fun i hi => ?_)
  have hrow := hDD i hi
  have hrow' : (((∑ j ∈ range 17, (if i = j then (0 : ℚ) else (Ek i j).aub aLo aHi)) : ℚ) : ℝ)
      ≤ (((Ek i i).lo aLo aHi : ℚ) : ℝ) := by exact_mod_cast hrow
  push_cast at hrow'
  refine le_trans ?_ (hrow'.trans (Kel.lo_le_ev _ hl0 hl hh))
  refine Finset.sum_le_sum fun j _ => ?_
  split_ifs
  · simp
  · exact Kel.abs_ev_le _ hl0 hl hh

/-! ## Block structure: evaluate the form at `(z, m)` -/

/-- `(z, m) ∈ ℝ¹⁴ × ℝ³` as one vector indexed by `ℕ`. -/
def jn (z m : ℕ → ℝ) (i : ℕ) : ℝ := if i < 14 then z i else m (i - 14)

lemma sum17 (f : ℕ → ℝ) : ∑ i ∈ range 17, f i = ∑ i ∈ range 14, f i + ∑ k ∈ range 3, f (14 + k) :=
  Finset.sum_range_add f 14 3

theorem block {a : ℝ} (ha : a ^ 4 = 20 * a ^ 2 - 80) (z m : ℕ → ℝ) :
    ∑ i ∈ range 17, ∑ j ∈ range 17, jn z m i * (Mk i j).ev a * jn z m j
      = (1 / 2) * ∑ i ∈ range 14, ∑ j ∈ range 14, z i * (Hd i j).ev a * z j
        - (eps : ℝ) * ∑ i ∈ range 14, z i ^ 2
        + ∑ b ∈ range 5, (∑ i ∈ range 14, (Kd i b).ev a * z i) ^ 2
        + ∑ i ∈ range 14, z i * ∑ k ∈ range 3, (Gd i k).ev a * m k
        + ∑ k ∈ range 3, ∑ l ∈ range 3, m k * ((cG * Gth k l : ℚ) : ℝ) * m l := by
  -- the four blocks
  have hzz : ∀ i ∈ range 14, ∀ j ∈ range 14, jn z m i * (Mk i j).ev a * jn z m j
      = (1 / 2) * (z i * (Hd i j).ev a * z j) - z i * (((if i = j then eps else 0 : ℚ)) : ℝ) * z j
        + ∑ b ∈ range 5, z i * ((Kd i b).ev a * (Kd j b).ev a) * z j := by
    intro i hi j hj
    have hi' : i < 14 := mem_range.1 hi
    have hj' : j < 14 := mem_range.1 hj
    simp only [jn, Mk, Mzz, pen, hi', hj', if_true, Kel.ev_add, Kel.ev_sub, Kel.ev_smul, Kel.ev_ofQ,
      Kel.ev_mul _ _ ha, Finset.sum_range_succ, Finset.sum_range_zero]
    push_cast; ring
  have hzm : ∀ i ∈ range 14, ∀ k ∈ range 3, jn z m i * (Mk i (14 + k)).ev a * jn z m (14 + k)
      = (1 / 2) * (z i * ((Gd i k).ev a * m k)) := by
    intro i hi k _
    have hi' : i < 14 := mem_range.1 hi
    simp only [jn, Mk, hi', if_true, show ¬ (14 + k < 14) by omega, if_false,
      show 14 + k - 14 = k by omega, Kel.ev_smul]
    push_cast; ring
  have hmz : ∀ k ∈ range 3, ∀ j ∈ range 14, jn z m (14 + k) * (Mk (14 + k) j).ev a * jn z m j
      = (1 / 2) * (z j * ((Gd j k).ev a * m k)) := by
    intro k _ j hj
    have hj' : j < 14 := mem_range.1 hj
    simp only [jn, Mk, hj', if_true, show ¬ (14 + k < 14) by omega, if_false,
      show 14 + k - 14 = k by omega, Kel.ev_smul]
    push_cast; ring
  have hmm : ∀ k ∈ range 3, ∀ l ∈ range 3, jn z m (14 + k) * (Mk (14 + k) (14 + l)).ev a * jn z m (14 + l)
      = m k * ((cG * Gth k l : ℚ) : ℝ) * m l := by
    intro k _ l _
    simp only [jn, Mk, show ¬ (14 + k < 14) by omega, show ¬ (14 + l < 14) by omega, if_false,
      show 14 + k - 14 = k by omega, show 14 + l - 14 = l by omega, Kel.ev_ofQ]
  have hdiag : ∑ i ∈ range 14, ∑ j ∈ range 14, z i * (((if i = j then eps else 0 : ℚ)) : ℝ) * z j
      = (eps : ℝ) * ∑ i ∈ range 14, z i ^ 2 := by
    rw [Finset.mul_sum]
    refine Finset.sum_congr rfl fun i hi => ?_
    rw [Finset.sum_eq_single i]
    · simp; ring
    · intro j _ hji; simp [Ne.symm hji]
    · intro h; exact absurd hi h
  have hpen : ∑ i ∈ range 14, ∑ j ∈ range 14, ∑ b ∈ range 5, z i * ((Kd i b).ev a * (Kd j b).ev a) * z j
      = ∑ b ∈ range 5, (∑ i ∈ range 14, (Kd i b).ev a * z i) ^ 2 := by
    calc _ = ∑ i ∈ range 14, ∑ b ∈ range 5, ∑ j ∈ range 14,
            z i * ((Kd i b).ev a * (Kd j b).ev a) * z j :=
          Finset.sum_congr rfl fun i _ => Finset.sum_comm
      _ = ∑ b ∈ range 5, ∑ i ∈ range 14, ∑ j ∈ range 14,
            z i * ((Kd i b).ev a * (Kd j b).ev a) * z j := Finset.sum_comm
      _ = _ := Finset.sum_congr rfl fun b _ => qf_rank1 (fun i => (Kd i b).ev a) z 14
  have b1 : ∑ i ∈ range 14, ∑ j ∈ range 14, jn z m i * (Mk i j).ev a * jn z m j
      = (1 / 2) * ∑ i ∈ range 14, ∑ j ∈ range 14, z i * (Hd i j).ev a * z j
        - (eps : ℝ) * ∑ i ∈ range 14, z i ^ 2
        + ∑ b ∈ range 5, (∑ i ∈ range 14, (Kd i b).ev a * z i) ^ 2 := by
    rw [Finset.sum_congr rfl fun i hi => Finset.sum_congr rfl fun j hj => hzz i hi j hj]
    simp only [Finset.sum_add_distrib, Finset.sum_sub_distrib, ← Finset.mul_sum]
    rw [hdiag, hpen]
  have b2 : ∑ i ∈ range 14, ∑ k ∈ range 3, jn z m i * (Mk i (14 + k)).ev a * jn z m (14 + k)
      = (1 / 2) * ∑ i ∈ range 14, z i * ∑ k ∈ range 3, (Gd i k).ev a * m k := by
    rw [Finset.sum_congr rfl fun i hi => Finset.sum_congr rfl fun k hk => hzm i hi k hk]
    simp only [← Finset.mul_sum]
  have b3 : ∑ k ∈ range 3, ∑ j ∈ range 14, jn z m (14 + k) * (Mk (14 + k) j).ev a * jn z m j
      = (1 / 2) * ∑ i ∈ range 14, z i * ∑ k ∈ range 3, (Gd i k).ev a * m k := by
    rw [Finset.sum_congr rfl fun k hk => Finset.sum_congr rfl fun j hj => hmz k hk j hj,
      Finset.sum_comm]
    simp only [← Finset.mul_sum]
  have b4 : ∑ k ∈ range 3, ∑ l ∈ range 3, jn z m (14 + k) * (Mk (14 + k) (14 + l)).ev a * jn z m (14 + l)
      = ∑ k ∈ range 3, ∑ l ∈ range 3, m k * ((cG * Gth k l : ℚ) : ℝ) * m l :=
    Finset.sum_congr rfl fun k hk => Finset.sum_congr rfl fun l hl => hmm k hk l hl
  simp only [sum17, Finset.sum_add_distrib]
  rw [b1, b2, b3, b4]
  ring

/-! ## The real α and the statement (C′) -/


/-- `m(σ) = (σ₁², σ₁σ₂, σ₂²)`. -/
def msig (σ₁ σ₂ : ℝ) (k : ℕ) : ℝ := if k = 0 then σ₁ ^ 2 else if k = 1 then σ₁ * σ₂ else σ₂ ^ 2

lemma gram_msig (σ₁ σ₂ : ℝ) :
    ∑ k ∈ range 3, ∑ l ∈ range 3, msig σ₁ σ₂ k * ((cG * Gth k l : ℚ) : ℝ) * msig σ₁ σ₂ l
      = (cG : ℝ) * (σ₁ ^ 2 + σ₂ ^ 2) ^ 2 := by
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, msig, Gth]
  norm_num [th]
  ring

/-- **Certificate (C′)** (`local/LOCAL_LEMMA.md` §3′), with the exported exact data:
for `z ⊥ {r₁, r₂, r₃, ŝ₁, ŝ₂}` (i.e. `z ∈ W`) and all `σ`,
`(1/16)|z|² + (29/500)|s|⁴ ≤ ½⟨z,Hz⟩ + ⟨Γ m(σ), z⟩ + (13/40)|s|⁴`, `|s|⁴ = (25/4)(σ₁²+σ₂²)²`. -/
theorem Cprime (z : ℕ → ℝ) (σ₁ σ₂ : ℝ)
    (hker : ∀ b ∈ range 5, ∑ i ∈ range 14, (Kd i b).ev alpha * z i = 0) :
    (1 / 16 : ℝ) * ∑ i ∈ range 14, z i ^ 2 + (29 / 500 : ℝ) * ((25 / 4) * (σ₁ ^ 2 + σ₂ ^ 2) ^ 2)
      ≤ (1 / 2) * ∑ i ∈ range 14, ∑ j ∈ range 14, z i * (Hd i j).ev alpha * z j
        + ∑ i ∈ range 14, z i * ∑ k ∈ range 3, (Gd i k).ev alpha * msig σ₁ σ₂ k
        + (13 / 40 : ℝ) * ((25 / 4) * (σ₁ ^ 2 + σ₂ ^ 2) ^ 2) := by
  have hpsd := M_psd alpha_box.1 alpha_box.2 (jn z (msig σ₁ σ₂))
  rw [block alpha_minpoly, gram_msig] at hpsd
  have hK : ∑ b ∈ range 5, (∑ i ∈ range 14, (Kd i b).ev alpha * z i) ^ 2 = 0 :=
    Finset.sum_eq_zero fun b hb => by rw [hker b hb]; ring
  rw [hK] at hpsd
  norm_num [eps, cG, qp] at hpsd ⊢
  linarith

end LocalCert

#print axioms LocalCert.certOK_true
#print axioms LocalCert.Cprime
