import LogLean.LocalFrames
import LogLean.LocalPairData

/-!
# LocalPairsA: pair-level Taylor-link identities `T6_g(atoms_ij(x)) = p_ij(x)` (T1), pairs [(0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (1, 2)]

GENERATED by `lean/gen/export_local_data.py pairs`; each identity is one `decide +kernel`
(`LocalSP.checkEq6`), turned into the real identity by `LocalSP.eq_of_checkEq6` in `LocalMain`.
-/

namespace LocalPairs
open LocalKel LocalSP LocalAtom LocalFrames LocalPairData

set_option profiler true in
theorem check01 : checkEq6 (T6of 0 1) (atA 0 1) (atB 0 1) (atC 0 1) (atCp 0 1) atRi atRj (pij 0 1) = true := by
  decide +kernel

set_option profiler true in
theorem check02 : checkEq6 (T6of 0 2) (atA 0 2) (atB 0 2) (atC 0 2) (atCp 0 2) atRi atRj (pij 0 2) = true := by
  decide +kernel

set_option profiler true in
theorem check03 : checkEq6 (T6of 0 3) (atA 0 3) (atB 0 3) (atC 0 3) (atCp 0 3) atRi atRj (pij 0 3) = true := by
  decide +kernel

set_option profiler true in
theorem check04 : checkEq6 (T6of 0 4) (atA 0 4) (atB 0 4) (atC 0 4) (atCp 0 4) atRi atRj (pij 0 4) = true := by
  decide +kernel

set_option profiler true in
theorem check05 : checkEq6 (T6of 0 5) (atA 0 5) (atB 0 5) (atC 0 5) (atCp 0 5) atRi atRj (pij 0 5) = true := by
  decide +kernel

set_option profiler true in
theorem check06 : checkEq6 (T6of 0 6) (atA 0 6) (atB 0 6) (atC 0 6) (atCp 0 6) atRi atRj (pij 0 6) = true := by
  decide +kernel

set_option profiler true in
theorem check12 : checkEq6 (T6of 1 2) (atA 1 2) (atB 1 2) (atC 1 2) (atCp 1 2) atRi atRj (pij 1 2) = true := by
  decide +kernel

end LocalPairs

#print axioms LocalPairs.check01
#print axioms LocalPairs.check02
#print axioms LocalPairs.check03
#print axioms LocalPairs.check04
#print axioms LocalPairs.check05
#print axioms LocalPairs.check06
#print axioms LocalPairs.check12
