import LogLean.LocalFrames
import LogLean.LocalPairData

/-!
# LocalPairsB: pair-level Taylor-link identities `T6_g(atoms_ij(x)) = p_ij(x)` (T1), pairs [(1, 3), (1, 4), (1, 5), (1, 6), (2, 3), (2, 4), (2, 5)]

GENERATED by `lean/gen/export_local_data.py pairs`; each identity is one `decide +kernel`
(`LocalSP.checkEq6`), turned into the real identity by `LocalSP.eq_of_checkEq6` in `LocalMain`.
-/

namespace LocalPairs
open LocalKel LocalSP LocalAtom LocalFrames LocalPairData

set_option profiler true in
theorem check13 : checkEq6 (T6of 1 3) (atA 1 3) (atB 1 3) (atC 1 3) (atCp 1 3) atRi atRj (pij 1 3) = true := by
  decide +kernel

set_option profiler true in
theorem check14 : checkEq6 (T6of 1 4) (atA 1 4) (atB 1 4) (atC 1 4) (atCp 1 4) atRi atRj (pij 1 4) = true := by
  decide +kernel

set_option profiler true in
theorem check15 : checkEq6 (T6of 1 5) (atA 1 5) (atB 1 5) (atC 1 5) (atCp 1 5) atRi atRj (pij 1 5) = true := by
  decide +kernel

set_option profiler true in
theorem check16 : checkEq6 (T6of 1 6) (atA 1 6) (atB 1 6) (atC 1 6) (atCp 1 6) atRi atRj (pij 1 6) = true := by
  decide +kernel

set_option profiler true in
theorem check23 : checkEq6 (T6of 2 3) (atA 2 3) (atB 2 3) (atC 2 3) (atCp 2 3) atRi atRj (pij 2 3) = true := by
  decide +kernel

set_option profiler true in
theorem check24 : checkEq6 (T6of 2 4) (atA 2 4) (atB 2 4) (atC 2 4) (atCp 2 4) atRi atRj (pij 2 4) = true := by
  decide +kernel

set_option profiler true in
theorem check25 : checkEq6 (T6of 2 5) (atA 2 5) (atB 2 5) (atC 2 5) (atCp 2 5) atRi atRj (pij 2 5) = true := by
  decide +kernel

end LocalPairs

#print axioms LocalPairs.check13
#print axioms LocalPairs.check14
#print axioms LocalPairs.check15
#print axioms LocalPairs.check16
#print axioms LocalPairs.check23
#print axioms LocalPairs.check24
#print axioms LocalPairs.check25
