import LogN7.S9493.Data
import ThomsonGen.Cert.Split
/-! Kernel check `checkMeta` of `tc_s9493`, one `decide` per block.
    Generated by `lean/gen_log/gen_split.py`; do not edit. -/

open Real

section LogN7_S9493_split
namespace LogN7
open ThomsonN7 ThomsonN7.Kron ThomsonN7.Kron.Ex ThomsonN7.Cert ThomsonN7.ThreePoint

set_option maxHeartbeats 0

theorem tc_s9493_mP0 : (tc_s9493.blkP 0).ok (tc_s9493.m 0) = true := by decide +kernel
theorem tc_s9493_mP1 : (tc_s9493.blkP 1).ok (tc_s9493.m 1) = true := by decide +kernel
theorem tc_s9493_mP2 : (tc_s9493.blkP 2).ok (tc_s9493.m 2) = true := by decide +kernel
theorem tc_s9493_mP3 : (tc_s9493.blkP 3).ok (tc_s9493.m 3) = true := by decide +kernel
theorem tc_s9493_mP4 : (tc_s9493.blkP 4).ok (tc_s9493.m 4) = true := by decide +kernel
theorem tc_s9493_mP5 : (tc_s9493.blkP 5).ok (tc_s9493.m 5) = true := by decide +kernel
theorem tc_s9493_mP6 : (tc_s9493.blkP 6).ok (tc_s9493.m 6) = true := by decide +kernel
theorem tc_s9493_mP : (List.range tc_s9493.K).all (fun k => (tc_s9493.blkP k).ok (tc_s9493.m k)) = true := by
  rw [show tc_s9493.K = 7 from rfl, show List.range 7 = [0, 1, 2, 3, 4, 5, 6] from rfl]
  simp only [List.all_cons, List.all_nil, tc_s9493_mP0, tc_s9493_mP1, tc_s9493_mP2, tc_s9493_mP3, tc_s9493_mP4, tc_s9493_mP5, tc_s9493_mP6, Bool.and_true, Bool.true_and, Bool.and_self]

theorem tc_s9493_mR0 : (tc_s9493.blkR 0).ok (tc_s9493.m 0) = true := by decide +kernel
theorem tc_s9493_mR1 : (tc_s9493.blkR 1).ok (tc_s9493.m 1) = true := by decide +kernel
theorem tc_s9493_mR2 : (tc_s9493.blkR 2).ok (tc_s9493.m 2) = true := by decide +kernel
theorem tc_s9493_mR3 : (tc_s9493.blkR 3).ok (tc_s9493.m 3) = true := by decide +kernel
theorem tc_s9493_mR4 : (tc_s9493.blkR 4).ok (tc_s9493.m 4) = true := by decide +kernel
theorem tc_s9493_mR5 : (tc_s9493.blkR 5).ok (tc_s9493.m 5) = true := by decide +kernel
theorem tc_s9493_mR6 : (tc_s9493.blkR 6).ok (tc_s9493.m 6) = true := by decide +kernel
theorem tc_s9493_mR : (List.range tc_s9493.K).all (fun k => (tc_s9493.blkR k).ok (tc_s9493.m k)) = true := by
  rw [show tc_s9493.K = 7 from rfl, show List.range 7 = [0, 1, 2, 3, 4, 5, 6] from rfl]
  simp only [List.all_cons, List.all_nil, tc_s9493_mR0, tc_s9493_mR1, tc_s9493_mR2, tc_s9493_mR3, tc_s9493_mR4, tc_s9493_mR5, tc_s9493_mR6, Bool.and_true, Bool.true_and, Bool.and_self]

theorem tc_s9493_mSA0 : okF (tc_s9493_SA0).z.length (tc_s9493_SA0).B = true := by decide +kernel
theorem tc_s9493_mSA1 : okF (tc_s9493_SA1).z.length (tc_s9493_SA1).B = true := by decide +kernel
theorem tc_s9493_mSA2 : okF (tc_s9493_SA2).z.length (tc_s9493_SA2).B = true := by decide +kernel
theorem tc_s9493_mSA3 : okF (tc_s9493_SA3).z.length (tc_s9493_SA3).B = true := by decide +kernel
theorem tc_s9493_mSA4 : okF (tc_s9493_SA4).z.length (tc_s9493_SA4).B = true := by decide +kernel
theorem tc_s9493_mSA5 : okF (tc_s9493_SA5).z.length (tc_s9493_SA5).B = true := by decide +kernel
theorem tc_s9493_mSA6 : okF (tc_s9493_SA6).z.length (tc_s9493_SA6).B = true := by decide +kernel
theorem tc_s9493_mSA7 : okF (tc_s9493_SA7).z.length (tc_s9493_SA7).B = true := by decide +kernel
theorem tc_s9493_mSA8 : okF (tc_s9493_SA8).z.length (tc_s9493_SA8).B = true := by decide +kernel
theorem tc_s9493_mSA : tc_s9493.SA.all (fun s => okF s.z.length s.B) = true := by
  rw [show tc_s9493.SA = [tc_s9493_SA0, tc_s9493_SA1, tc_s9493_SA2, tc_s9493_SA3, tc_s9493_SA4, tc_s9493_SA5, tc_s9493_SA6, tc_s9493_SA7, tc_s9493_SA8] from rfl]
  simp only [List.all_cons, List.all_nil, tc_s9493_mSA0, tc_s9493_mSA1, tc_s9493_mSA2, tc_s9493_mSA3, tc_s9493_mSA4, tc_s9493_mSA5, tc_s9493_mSA6, tc_s9493_mSA7, tc_s9493_mSA8, Bool.and_true, Bool.true_and, Bool.and_self]

theorem tc_s9493_mSB0 : okF (tc_s9493_SB0).z.length (tc_s9493_SB0).B = true := by decide +kernel
theorem tc_s9493_mSB1 : okF (tc_s9493_SB1).z.length (tc_s9493_SB1).B = true := by decide +kernel
theorem tc_s9493_mSB2 : okF (tc_s9493_SB2).z.length (tc_s9493_SB2).B = true := by decide +kernel
theorem tc_s9493_mSB3 : okF (tc_s9493_SB3).z.length (tc_s9493_SB3).B = true := by decide +kernel
theorem tc_s9493_mSB4 : okF (tc_s9493_SB4).z.length (tc_s9493_SB4).B = true := by decide +kernel
theorem tc_s9493_mSB5 : okF (tc_s9493_SB5).z.length (tc_s9493_SB5).B = true := by decide +kernel
theorem tc_s9493_mSB6 : okF (tc_s9493_SB6).z.length (tc_s9493_SB6).B = true := by decide +kernel
theorem tc_s9493_mSB7 : okF (tc_s9493_SB7).z.length (tc_s9493_SB7).B = true := by decide +kernel
theorem tc_s9493_mSB : tc_s9493.SB.all (fun s => okF s.z.length s.B) = true := by
  rw [show tc_s9493.SB = [tc_s9493_SB0, tc_s9493_SB1, tc_s9493_SB2, tc_s9493_SB3, tc_s9493_SB4, tc_s9493_SB5, tc_s9493_SB6, tc_s9493_SB7] from rfl]
  simp only [List.all_cons, List.all_nil, tc_s9493_mSB0, tc_s9493_mSB1, tc_s9493_mSB2, tc_s9493_mSB3, tc_s9493_mSB4, tc_s9493_mSB5, tc_s9493_mSB6, tc_s9493_mSB7, Bool.and_true, Bool.true_and, Bool.and_self]

theorem tc_s9493_mSG0 : okF (tc_s9493_SG0).z.length (tc_s9493_SG0).B = true := by decide +kernel
theorem tc_s9493_mSG1 : okF (tc_s9493_SG1).z.length (tc_s9493_SG1).B = true := by decide +kernel
theorem tc_s9493_mSG2 : okF (tc_s9493_SG2).z.length (tc_s9493_SG2).B = true := by decide +kernel
theorem tc_s9493_mSG3 : okF (tc_s9493_SG3).z.length (tc_s9493_SG3).B = true := by decide +kernel
theorem tc_s9493_mSG4 : okF (tc_s9493_SG4).z.length (tc_s9493_SG4).B = true := by decide +kernel
theorem tc_s9493_mSG5 : okF (tc_s9493_SG5).z.length (tc_s9493_SG5).B = true := by decide +kernel
theorem tc_s9493_mSG6 : okF (tc_s9493_SG6).z.length (tc_s9493_SG6).B = true := by decide +kernel
theorem tc_s9493_mSG7 : okF (tc_s9493_SG7).z.length (tc_s9493_SG7).B = true := by decide +kernel
theorem tc_s9493_mSG : tc_s9493.SG.all (fun s => okF s.z.length s.B) = true := by
  rw [show tc_s9493.SG = [tc_s9493_SG0, tc_s9493_SG1, tc_s9493_SG2, tc_s9493_SG3, tc_s9493_SG4, tc_s9493_SG5, tc_s9493_SG6, tc_s9493_SG7] from rfl]
  simp only [List.all_cons, List.all_nil, tc_s9493_mSG0, tc_s9493_mSG1, tc_s9493_mSG2, tc_s9493_mSG3, tc_s9493_mSG4, tc_s9493_mSG5, tc_s9493_mSG6, tc_s9493_mSG7, Bool.and_true, Bool.true_and, Bool.and_self]

theorem tc_s9493_meta : tc_s9493.checkMeta = true :=
  TCert.checkMeta_of_parts tc_s9493 (by decide +kernel) (by decide +kernel) (by decide +kernel)
    (by decide +kernel) (by decide +kernel) (by decide +kernel)
    tc_s9493_mP tc_s9493_mR tc_s9493_mSA tc_s9493_mSB tc_s9493_mSG
end LogN7
end LogN7_S9493_split
