import CoulN7.Cap.Data
import CoulN7.Cap.ChkSA0
import CoulN7.Cap.ChkSA1
import CoulN7.Cap.ChkSA2
import CoulN7.Cap.ChkSA3
import CoulN7.Cap.ChkSA4
import CoulN7.Cap.ChkSA5
import CoulN7.Cap.ChkSA6
import CoulN7.Cap.ChkSA7
import CoulN7.Cap.ChkSA8
import CoulN7.Cap.ChkSB0
import CoulN7.Cap.ChkSB1
import CoulN7.Cap.ChkSB2
import CoulN7.Cap.ChkSB3
import CoulN7.Cap.ChkSB4
import CoulN7.Cap.ChkSB5
import CoulN7.Cap.ChkSB6
import CoulN7.Cap.ChkSB7
import CoulN7.Cap.ChkSG0
import CoulN7.Cap.ChkSG1
import CoulN7.Cap.ChkSG2
import CoulN7.Cap.ChkSG3
import CoulN7.Cap.ChkSG4
import CoulN7.Cap.ChkSG5
import CoulN7.Cap.ChkSG6
import CoulN7.Cap.ChkSG7
/-! Kernel check `checkMeta` of Cap, assembled from `checkMetaF` and the per-block checks.
    Generated by `numerics/n7_interval/lean/gen/gen_capchk.py Cap` from the `TCertN` data of Cap.
    Row-wise kernel checks (one `decide` per row; a whole-block `decide` exceeds ~10 GB).  Regenerate; do not edit. -/

open Real

section CoulN7_Cap_tc
namespace CoulN7
open ThomsonN7 ThomsonN7.Kron ThomsonN7.Kron.Ex ThomsonN7.Cert ThomsonN7.ThreePoint

-- large literal lists: elaboration budget only (no effect on what is checked)
set_option maxHeartbeats 0

theorem tc_cap_metaF : tc_cap.checkMetaF = true := by decide +kernel

theorem tc_cap_meta : tc_cap.checkMeta = true :=
  tc_cap.checkMeta_of_parts tc_cap_metaF
    (by
    show List.all [tc_cap_SA0, tc_cap_SA1, tc_cap_SA2, tc_cap_SA3, tc_cap_SA4, tc_cap_SA5, tc_cap_SA6, tc_cap_SA7, tc_cap_SA8] TBlkN.okN = true
    simp only [List.all_cons, List.all_nil, Bool.and_true, tc_cap_SA0_ok, tc_cap_SA1_ok, tc_cap_SA2_ok, tc_cap_SA3_ok, tc_cap_SA4_ok, tc_cap_SA5_ok, tc_cap_SA6_ok, tc_cap_SA7_ok, tc_cap_SA8_ok])
    (by
    show List.all [tc_cap_SB0, tc_cap_SB1, tc_cap_SB2, tc_cap_SB3, tc_cap_SB4, tc_cap_SB5, tc_cap_SB6, tc_cap_SB7] TBlkN.okN = true
    simp only [List.all_cons, List.all_nil, Bool.and_true, tc_cap_SB0_ok, tc_cap_SB1_ok, tc_cap_SB2_ok, tc_cap_SB3_ok, tc_cap_SB4_ok, tc_cap_SB5_ok, tc_cap_SB6_ok, tc_cap_SB7_ok])
    (by
    show List.all [tc_cap_SG0, tc_cap_SG1, tc_cap_SG2, tc_cap_SG3, tc_cap_SG4, tc_cap_SG5, tc_cap_SG6, tc_cap_SG7] TBlkN.okN = true
    simp only [List.all_cons, List.all_nil, Bool.and_true, tc_cap_SG0_ok, tc_cap_SG1_ok, tc_cap_SG2_ok, tc_cap_SG3_ok, tc_cap_SG4_ok, tc_cap_SG5_ok, tc_cap_SG6_ok, tc_cap_SG7_ok])

end CoulN7
end CoulN7_Cap_tc
