import CoulN7.Cap.ChkMeta
import CoulN7.Cap.ChkA
import CoulN7.Cap.ChkB
import CoulN7.Cap.ChkG
import CoulN7.Bridge
import CoulN7.Minor.Cap
/-! Cap: `ThomsonGen.CapSpec φ₁ (1/165000) (-99/100)` (Coulomb) from the checked facially reduced certificate
`tc_cap` (`Cert.TCertN`, re-rounded, not sharp: E(P) − ef ≤ U − ef = 7.2962e-17 ≤ δ = 10⁻¹⁶) and the
coercive minorants of `CoulN7.Minor.MCap` (identified through `scaledEq`).  Coercivity windows: half-width
8000/(100·2²⁴) = 4.77·10⁻⁶ < τ₀ = 1/165000 around −1, 0 and grid roundings of c₁, c₂.
Generated by `numerics/n7_interval/lean/gen/gen_spec1.py`; do not edit. -/

open Real
namespace CoulN7
namespace Cap
open ThomsonN7 ThomsonN7.Cert ThomsonGen
open LogLean.Minor (peval)

theorem e_eq : tc_cap.toTCert.e = 24617129886703240133704224366008811520 := rfl
theorem lam_eq : tc_cap.toTCert.Lam = 1703256649559324941461443191274209280 := rfl
theorem an_eq : tc_cap.toTCert.an = -1 := rfl
theorem ad_eq : tc_cap.toTCert.ad = 1 := rfl
theorem bn_eq : tc_cap.toTCert.bn = -99 := rfl
theorem bd_eq : tc_cap.toTCert.bd = 100 := rfl
theorem lam_pos : 0 < tc_cap.toTCert.Lam := by rw [lam_eq]; norm_num
theorem alo_eq : tc_cap.toTCert.alo = -1 := by
  unfold TCert.alo; rw [an_eq, ad_eq]; norm_num
theorem ahi_eq : tc_cap.toTCert.ahi = (-99 / 100 : ℝ) := by
  unfold TCert.ahi; rw [bn_eq, bd_eq]; norm_num
/-- `E(P) ≤ ef + δ`, `δ = 10⁻¹⁶`. -/
theorem ef_ge : pairEnergy ThomsonN7.Base.phi pentBipyramid ≤ tc_cap.toTCert.ef + 1 / 10 ^ 16 := by
  refine pairEnergy_pent_le.trans ?_
  unfold TCert.ef; rw [e_eq, lam_eq]; norm_num
theorem eA : scaledEq CoulN7.Minor.MCap.HAd tc_cap.toTCert.HA tc_cap.toTCert.Lam CoulN7.Minor.MCap.HA = true := by decide +kernel
theorem eB : scaledEq CoulN7.Minor.MCap.HBd tc_cap.toTCert.HB tc_cap.toTCert.Lam CoulN7.Minor.MCap.HB = true := by decide +kernel
theorem eC : scaledEq CoulN7.Minor.MCap.HCd tc_cap.toTCert.HC tc_cap.toTCert.Lam CoulN7.Minor.MCap.HC = true := by decide +kernel

theorem capA (t : ℝ) (h1 : -1 ≤ t) (h2 : t ≤ (-99 / 100 : ℝ)) :
    peval CoulN7.Minor.MCap.HA t / CoulN7.Minor.MCap.HAd ≤ ThomsonN7.Base.phi t ∧
    (ThomsonN7.Base.phi t - peval CoulN7.Minor.MCap.HA t / CoulN7.Minor.MCap.HAd ≤ 1 / 10 ^ 16 → |t + 1| ≤ 1 / 165000) := by
  refine ⟨CoulN7.Minor.MCap.HA_le t h1 h2, fun h => ?_⟩
  have w := CoulN7.Minor.MCap.HA_coerc t h1 h2 h
  rw [CoulN7.Minor.MCap.D_eq] at w
  push_cast at w
  rw [abs_le]
  constructor <;> linarith [w.1, w.2]

theorem capB (t : ℝ) (h1 : -1 ≤ t) (h2 : t < 1) :
    peval CoulN7.Minor.MCap.HB t / CoulN7.Minor.MCap.HBd ≤ ThomsonN7.Base.phi t ∧
    (ThomsonN7.Base.phi t - peval CoulN7.Minor.MCap.HB t / CoulN7.Minor.MCap.HBd ≤ 1 / 10 ^ 16 → |t| ≤ 1 / 165000) := by
  refine ⟨CoulN7.Minor.MCap.HB_le t h1 h2, fun h => ?_⟩
  have w := CoulN7.Minor.MCap.HB_coerc t h1 h2 h
  rw [CoulN7.Minor.MCap.D_eq] at w
  push_cast at w
  rw [abs_le]
  constructor <;> linarith [w.1, w.2]

theorem capC (t : ℝ) (h1 : -1 ≤ t) (h2 : t < 1) :
    peval CoulN7.Minor.MCap.HC t / CoulN7.Minor.MCap.HCd ≤ ThomsonN7.Base.phi t ∧
    (ThomsonN7.Base.phi t - peval CoulN7.Minor.MCap.HC t / CoulN7.Minor.MCap.HCd ≤ 1 / 10 ^ 16 →
      |t - (-1 + √5) / 4| ≤ 1 / 165000 ∨ |t - (-1 - √5) / 4| ≤ 1 / 165000) := by
  refine ⟨CoulN7.Minor.MCap.HC_le t h1 h2, fun h => ?_⟩
  have w := CoulN7.Minor.MCap.HC_coerc t h1 h2 h
  rw [CoulN7.Minor.MCap.D_eq] at w
  push_cast at w
  obtain ⟨l5, u5⟩ := sqrt5_enc
  rcases w with w | w
  · right
    rw [abs_le]
    constructor <;> linarith [w.1, w.2]
  · left
    rw [abs_le]
    constructor <;> linarith [w.1, w.2]

/-- **The Coulomb cap.** -/
theorem spec : CapSpec ThomsonN7.Base.phi (1 / 165000) (-99 / 100 : ℝ) :=
  capSpec_of_minorN tc_cap tc_cap_meta tc_cap_A tc_cap_B tc_cap_G alo_eq ahi_eq ef_ge lam_pos
    (by decide) (by decide) (by decide) eA eB eC capA capB capC

end Cap
end CoulN7
