import Riesz2.Cap.Data
/-! Kernel check `chkG` of Cap.
    Generated by `lean/gen_riesz2/emit_tcert.py --tcertn` from `cert_cap_riesz2_D12_dyadic.json` (sha256 5266b1476990c48a…).
    Facially reduced typed certificate `TCertN` (ThomsonGen/Cert/NBlk.lean).  Regenerate; do not edit. -/

open Real

section Riesz2_Cap_tc
namespace Riesz2
open ThomsonN7 ThomsonN7.Kron ThomsonN7.Kron.Ex ThomsonN7.Cert ThomsonN7.ThreePoint

theorem tc_cap_G : tc_cap.chkG = true := by decide +kernel

end Riesz2
end Riesz2_Cap_tc
