import Riesz2.Cap.Data
import Riesz2.Cap.ChkSA0
import Riesz2.Cap.ChkSA1
import Riesz2.Cap.ChkSA2
import Riesz2.Cap.ChkSA3
import Riesz2.Cap.ChkSA4
import Riesz2.Cap.ChkSA5
import Riesz2.Cap.ChkSA6
import Riesz2.Cap.ChkSA7
import Riesz2.Cap.ChkSA8
import Riesz2.Cap.ChkSB0
import Riesz2.Cap.ChkSB1
import Riesz2.Cap.ChkSB2
import Riesz2.Cap.ChkSB3
import Riesz2.Cap.ChkSB4
import Riesz2.Cap.ChkSB5
import Riesz2.Cap.ChkSB6
import Riesz2.Cap.ChkSB7
import Riesz2.Cap.ChkSG0
import Riesz2.Cap.ChkSG1
import Riesz2.Cap.ChkSG2
import Riesz2.Cap.ChkSG3
import Riesz2.Cap.ChkSG4
import Riesz2.Cap.ChkSG5
import Riesz2.Cap.ChkSG6
import Riesz2.Cap.ChkSG7
/-! Kernel check `checkMeta` of Cap, assembled from `checkMetaF` and the per-block checks.
    Generated by `lean/gen_riesz2/gen_capchk.py Cap` from the `TCertN` data of Cap.
    Row-wise kernel checks (one `decide` per row; a whole-block `decide` exceeds ~10 GB).  Regenerate; do not edit. -/

open Real

section Riesz2_Cap_tc
namespace Riesz2
open ThomsonN7 ThomsonN7.Kron ThomsonN7.Kron.Ex ThomsonN7.Cert ThomsonN7.ThreePoint

-- large literal lists: elaboration budget only (no effect on what is checked)
set_option maxHeartbeats 0

theorem tc_cap_metaF : tc_cap.checkMetaF = true := by decide +kernel

theorem tc_cap_meta : tc_cap.checkMeta = true :=
  tc_cap.checkMeta_of_parts tc_cap_metaF
    (by
    show List.all [tc_cap_SA0, tc_cap_SA1, tc_cap_SA2, tc_cap_SA3, tc_cap_SA4, tc_cap_SA5, tc_cap_SA6, tc_cap_SA7, tc_cap_SA8] TBlkN.okN = true
    simp only [List.all_cons, List.all_nil, Bool.and_true, tc_cap_SA0_ok, tc_cap_SA1_ok, tc_cap_SA2_ok, tc_cap_SA3_ok, tc_cap_SA4_ok, tc_cap_SA5_ok, tc_cap_SA6_ok, tc_cap_SA7_ok, tc_cap_SA8_ok])
    (by
    show List.all [tc_cap_SB0, tc_cap_SB1, tc_cap_SB2, tc_cap_SB3, tc_cap_SB4, tc_cap_SB5, tc_cap_SB6, tc_cap_SB7] TBlkN.okN = true
    simp only [List.all_cons, List.all_nil, Bool.and_true, tc_cap_SB0_ok, tc_cap_SB1_ok, tc_cap_SB2_ok, tc_cap_SB3_ok, tc_cap_SB4_ok, tc_cap_SB5_ok, tc_cap_SB6_ok, tc_cap_SB7_ok])
    (by
    show List.all [tc_cap_SG0, tc_cap_SG1, tc_cap_SG2, tc_cap_SG3, tc_cap_SG4, tc_cap_SG5, tc_cap_SG6, tc_cap_SG7] TBlkN.okN = true
    simp only [List.all_cons, List.all_nil, Bool.and_true, tc_cap_SG0_ok, tc_cap_SG1_ok, tc_cap_SG2_ok, tc_cap_SG3_ok, tc_cap_SG4_ok, tc_cap_SG5_ok, tc_cap_SG6_ok, tc_cap_SG7_ok])

end Riesz2
end Riesz2_Cap_tc
