import Riesz2.Cap.ChkMeta
import Riesz2.Cap.ChkA
import Riesz2.Cap.ChkB
import Riesz2.Cap.ChkG
import Riesz2.Bridge
import Riesz2.MinorCap
/-! Cap: `Riesz2.CapSpecSharp phi2 (-99/100)` from the checked facially reduced certificate `tc_cap`
(`Cert.TCertN`, e = 41/4 EXACTLY) and the sharp minorants of `Riesz2.Minor.Cap` (exact contact sets).
Generated by lean/gen_riesz2/gen_spec2.py; do not edit. -/

open Real
namespace Riesz2
namespace Cap
open Minor ThomsonN7.Cert

theorem e_eq : tc_cap.toTCert.e = 25064026220673171770572800000 := rfl
theorem lam_eq : tc_cap.toTCert.Lam = 2445270850797382611763200000 := rfl
theorem an_eq : tc_cap.toTCert.an = -1 := rfl
theorem ad_eq : tc_cap.toTCert.ad = 1 := rfl
theorem bn_eq : tc_cap.toTCert.bn = -99 := rfl
theorem bd_eq : tc_cap.toTCert.bd = 100 := rfl
theorem lam_pos : 0 < tc_cap.toTCert.Lam := by rw [lam_eq]; norm_num
theorem alo_eq : tc_cap.toTCert.alo = -1 := by
  unfold TCert.alo; rw [an_eq, ad_eq]; norm_num
theorem ahi_eq : tc_cap.toTCert.ahi = (-99 / 100 : ℝ) := by
  unfold TCert.ahi; rw [bn_eq, bd_eq]; norm_num
/-- exactly sharp: `e / Λ = 41/4`. -/
theorem ef_ge : (41 / 4 : ℝ) ≤ tc_cap.toTCert.ef := by
  unfold TCert.ef; rw [e_eq, lam_eq]; norm_num
theorem eA : scaledEq Minor.Cap.HAd tc_cap.toTCert.HA tc_cap.toTCert.Lam Minor.Cap.HA = true := by decide +kernel
theorem eB : scaledEq Minor.Cap.HBd tc_cap.toTCert.HB tc_cap.toTCert.Lam Minor.Cap.HB = true := by decide +kernel
theorem eC : scaledEq Minor.Cap.HCd tc_cap.toTCert.HC tc_cap.toTCert.Lam Minor.Cap.HC = true := by decide +kernel

/-- **The sharp cap.** -/
theorem spec : CapSpecSharp phi2 (-99 / 100 : ℝ) :=
  capSpecSharp_of_minorN tc_cap tc_cap_meta tc_cap_A tc_cap_B tc_cap_G alo_eq ahi_eq ef_ge lam_pos
    (by decide) (by decide) (by decide) eA eB eC
    (fun t h1 h2 => Minor.Cap.capA h1 h2) (fun t h1 h2 => Minor.Cap.capB h1 h2)
    (fun t h1 h2 => Minor.Cap.capC h1 h2)

end Cap
end Riesz2
