import CoulN7.S9493.ChkMeta
import CoulN7.S9493.ChkA
import CoulN7.S9493.ChkB
import CoulN7.S9493.ChkG
import CoulN7.Bridge
import CoulN7.Minor.S9493
/-! Slab S9493: `ThomsonGen.SlabSpec φ₁ (-47 / 50 : ℝ) (-93 / 100 : ℝ)` (Coulomb) from the checked packed certificate `tc_s9493` and
the minorants of `CoulN7.Minor.MS9493` (identified through `scaledEq`).
Generated by `numerics/n7_interval/lean/gen/gen_spec1.py`; do not edit. -/

open Real
namespace CoulN7
namespace S9493
open ThomsonN7 ThomsonN7.Cert ThomsonGen

theorem e_eq : tc_s9493.e = 266610559930686210048 := rfl
theorem lam_eq : tc_s9493.Lam = 18446744073709551616 := rfl
theorem an_eq : tc_s9493.an = -47 := rfl
theorem ad_eq : tc_s9493.ad = 50 := rfl
theorem bn_eq : tc_s9493.bn = -93 := rfl
theorem bd_eq : tc_s9493.bd = 100 := rfl
theorem lam_pos : 0 < tc_s9493.Lam := by rw [lam_eq]; norm_num
theorem alo_eq : tc_s9493.alo = (-47 / 50 : ℝ) := by
  unfold TCert.alo; rw [an_eq, ad_eq]; norm_num
theorem ahi_eq : tc_s9493.ahi = (-93 / 100 : ℝ) := by
  unfold TCert.ahi; rw [bn_eq, bd_eq]; norm_num
/-- `E(P) < ef` (margin 1.000e-05). -/
theorem ef_gt : pairEnergy ThomsonN7.Base.phi pentBipyramid < tc_s9493.ef := by
  refine lt_of_le_of_lt pairEnergy_pent_le ?_
  unfold TCert.ef; rw [e_eq, lam_eq]; norm_num
theorem eA : scaledEq CoulN7.Minor.MS9493.HAd tc_s9493.HA tc_s9493.Lam CoulN7.Minor.MS9493.HA = true := by decide +kernel
theorem eB : scaledEq CoulN7.Minor.MS9493.HBd tc_s9493.HB tc_s9493.Lam CoulN7.Minor.MS9493.HB = true := by decide +kernel
theorem eC : scaledEq CoulN7.Minor.MS9493.HCd tc_s9493.HC tc_s9493.Lam CoulN7.Minor.MS9493.HC = true := by decide +kernel

/-- **Slab S9493.** -/
theorem spec : SlabSpec ThomsonN7.Base.phi (-47 / 50 : ℝ) (-93 / 100 : ℝ) :=
  slabSpec_of_minor tc_s9493 tc_s9493_meta tc_s9493_A tc_s9493_B tc_s9493_G alo_eq ahi_eq ef_gt lam_pos
    (by decide) (by decide) (by decide) eA eB eC
    (fun t h1 h2 => CoulN7.Minor.MS9493.HA_le t h1 h2) (fun t h1 h2 => CoulN7.Minor.MS9493.HB_le t h1 h2)
    (fun t h1 h2 => CoulN7.Minor.MS9493.HC_le t h1 h2)

end S9493
end CoulN7
