import Riesz2.S9998.Data
/-! Kernel check `chkB` of the slab S9998.
    Generated by `lean/gen_riesz2/emit_tcert.py` from `cert_slab_99_98_riesz2.json` (sha256 b3549168795447af…).
    Riesz s = 2 kernel `phi2 t = 1/(2-2t)`; format = upstream `TCert` (ThomsonGen/CertT.lean).
    Regenerate; do not edit. -/

open Real

section Riesz2_S9998_tc
namespace Riesz2
open ThomsonN7 ThomsonN7.Kron ThomsonN7.Kron.Ex ThomsonN7.Cert ThomsonN7.ThreePoint

theorem tc_s9998_B : tc_s9998.chkB = true := by decide +kernel

end Riesz2
end Riesz2_S9998_tc
