import Riesz2.S9998.ChkMeta
import Riesz2.S9998.ChkA
import Riesz2.S9998.ChkB
import Riesz2.S9998.ChkG
import Riesz2.Bridge
import Riesz2.MinorS9998
/-! Slab S9998: `ThomsonGen.SlabSpec phi2 -99/100 -49/50` from the checked packed certificate `tc_s9998`
and the 1-D minorants of `Riesz2.Minor.S9998` (identified through `scaledEq`).
Generated by lean/gen_riesz2/gen_spec2.py; do not edit. -/

open Real
namespace Riesz2
namespace S9998
open Minor ThomsonN7.Cert

theorem e_eq : tc_s9998.e = 189084660778745004032 := rfl
theorem lam_eq : tc_s9998.Lam = 18446744073709551616 := rfl
theorem an_eq : tc_s9998.an = -99 := rfl
theorem ad_eq : tc_s9998.ad = 100 := rfl
theorem bn_eq : tc_s9998.bn = -49 := rfl
theorem bd_eq : tc_s9998.bd = 50 := rfl
theorem lam_pos : 0 < tc_s9998.Lam := by rw [lam_eq]; norm_num
theorem alo_eq : tc_s9998.alo = (-99 / 100 : ℝ) := by
  unfold TCert.alo; rw [an_eq, ad_eq]; norm_num
theorem ahi_eq : tc_s9998.ahi = (-49 / 50 : ℝ) := by
  unfold TCert.ahi; rw [bn_eq, bd_eq]; norm_num
theorem ef_gt : (41 / 4 : ℝ) < tc_s9998.ef := by
  unfold TCert.ef; rw [e_eq, lam_eq]; norm_num
theorem eA : scaledEq Minor.S9998.HAd tc_s9998.HA tc_s9998.Lam Minor.S9998.HA = true := by decide +kernel
theorem eB : scaledEq Minor.S9998.HBd tc_s9998.HB tc_s9998.Lam Minor.S9998.HB = true := by decide +kernel
theorem eC : scaledEq Minor.S9998.HCd tc_s9998.HC tc_s9998.Lam Minor.S9998.HC = true := by decide +kernel

/-- **Slab S9998.** -/
theorem spec : ThomsonGen.SlabSpec phi2 (-99 / 100 : ℝ) (-49 / 50 : ℝ) :=
  slabSpec_of_minor tc_s9998 tc_s9998_meta tc_s9998_A tc_s9998_B tc_s9998_G alo_eq ahi_eq ef_gt lam_pos
    (by decide) (by decide) (by decide) eA eB eC
    (fun t h1 h2 => Minor.S9998.HA_le h1 h2) (fun t h1 h2 => Minor.S9998.HB_le h1 h2)
    (fun t h1 h2 => Minor.S9998.HC_le h1 h2)

end S9998
end Riesz2
