"""Run all exact checks of the case split and write COVERAGE.md at the repository root.

usage: python3 checkers/make_coverage.py      (from anywhere; paths are resolved relative to this file)
"""
import json, os, subprocess, sys, time, hashlib
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
CERTS = os.path.join(ROOT, "certificates")
sys.path.insert(0, HERE)
import check_cell, check_minorant_cell

CELLS = json.load(open(os.path.join(CERTS, "cells.json")))   # [{"name", "cert", "range"}] in covering order
T0 = time.time()


def sha(p):
    return hashlib.sha256(open(p, "rb").read()).hexdigest()[:12]


def rel(p):
    return os.path.relpath(p, ROOT)


rows = []
allok = True
# ---- cap (checked by check_cert.py / check_minorant.py)
capc = os.path.join(CERTS, "cert_cap_log_D12.json")
r1 = subprocess.run([sys.executable, os.path.join(HERE, "check_cert.py"), capc], capture_output=True, text=True)
r2 = subprocess.run([sys.executable, os.path.join(HERE, "check_minorant.py"), capc, "1e-16"], capture_output=True, text=True)
j1 = json.loads(r1.stdout[r1.stdout.index("{"):]); j2 = json.loads(r2.stdout[r2.stdout.index("{"):])
print(f"[{time.time() - T0:7.1f}s] cap: ALL_OK={j1['ALL_OK']} MINORANT_OK={j2.get('MINORANT_OK')}", flush=True)
import mpmath as mp
from fractions import Fraction as Fr
mp.mp.dps = 60
e = Fr(json.load(open(capc))["e"])
capm = mp.nstr(mp.mpf(e.numerator) / e.denominator + mp.log(1600 * mp.sqrt(5)), 60)
rows.append(("cap (Case 2)", "t01 in [-1, -99/100]", 12, capm + " (< 0 by design; the cap is closed by coercivity + local lemma)",
             "ALL_OK (check_cert.py)" if j1["ALL_OK"] else "FAIL",
             "MINORANT_OK, coercivity OK (check_minorant.py)" if j2.get("MINORANT_OK") and j2["coercivity"]["OK"] else "FAIL",
             rel(capc), sha(capc)))
allok &= j1["ALL_OK"] and j2.get("MINORANT_OK", False) and j2["coercivity"]["OK"]
for c in CELLS:
    p = os.path.join(CERTS, c["cert"])
    rc = check_cell.check(p, verbose=False)
    rm = check_minorant_cell.check(p)
    ok = rc["ALL_OK"] and rm["MINORANT_OK"]
    allok &= ok
    print(f"[{time.time() - T0:7.1f}s] {c['name']}: ALL_OK={rc['ALL_OK']} MINORANT_OK={rm['MINORANT_OK']}", flush=True)
    rows.append((c["name"], c["range"], rc["D"], rc["e_minus_EP"],
                 ("ALL_OK" if rc["ALL_OK"] else "FAIL") + f" (identities exact, all {'blocks PD' if rc['all_blocks_positive_definite'] else 'PD FAIL'}"
                 + f", sanity err {rc['sanity']['max_identity_error']})",
                 ("MINORANT_OK" if rm["MINORANT_OK"] else "FAIL") + f": phi-H > 1e-7 certified on "
                 + ", ".join(f"{k} {v['range'][0]}..{v['range'][1]}" for k, v in rm.items() if isinstance(v, dict) and "range" in v),
                 rel(p), sha(p)))
with open(os.path.join(ROOT, "COVERAGE.md"), "w") as fh:
    fh.write("# Coverage of the case split (log kernel), exact certificates\n\n")
    fh.write(f"Generated by `checkers/make_coverage.py` on {time.strftime('%Y-%m-%d %H:%M')}. E(P) = -log(1600 sqrt5). "
             "Every row is re-checked from the JSON by the checkers when this file is generated.\n\n")
    fh.write("| cell | range | degree | e - E(P) (exact e, 60 digits) | checker result | minorant check | certificate (sha256/12) |\n")
    fh.write("|---|---|---|---|---|---|---|\n")
    for r in rows:
        fh.write(f"| {r[0]} | {r[1]} | {r[2]} | {r[3]} | {r[4]} | {r[5]} | `{r[6]}` ({r[7]}) |\n")
    fh.write(f"\n**Overall: {'ALL CELLS OK' if allok else 'SOME CHECK FAILED'}.**\n")
    notes = os.path.join(HERE, "COVERAGE_notes.md")
    fh.write(open(notes).read() if os.path.exists(notes) else "")
print(f"[{time.time() - T0:7.1f}s] COVERAGE", "ALL CELLS OK" if allok else "FAILED")
sys.exit(0 if allok else 1)
