/-
Riesz2/MinorCase1.lean — Case 1 minorant H ≤ φ₂ on [-9/10, 1)
Generated by lean/gen_riesz2/gen_minor2.py; every Bool check was simulated exactly. Do not edit.
-/
import Riesz2.MinorCore

namespace Riesz2.Minor

namespace Case1

def D : ℕ := 409600
theorem D_eq : D = 409600 := rfl

def H : List ℤ := [9007165247442086, 9008189640473878, 8991327002498940, 9012013653216584, 9364826217321508, 9009556754782486, 6029807146928236, 6599073608361906, 16824134908684160, 20505166873647852, 8480895580225569]
def Hd : ℕ := 18014398509481984
def Q : List ℤ := [34007298906, -1024393031792, 16862637974938, -20686650717644, -352812564104924, 355269462539022, 2979749607854250, -569266461433670, -10225061300322254, -3681031964963692, 12024271293422283, 8480895580225569]
def Qd : ℕ := 9007199254740992
def ps : List (ℤ × ℤ) := [(-368640, -271360), (-271360, -186240), (-186240, -37280), (-37280, 18580), (18580, 67457), (67457, 110224), (110224, 185068), (185068, 213134), (213134, 225413), (225413, 236924), (236924, 409600)]
theorem id : gapId H Hd [1] Q Qd = true := by decide +kernel
theorem ch : posChainOK Q D ps (-368640) (409600) = true := by decide +kernel
/-- class : `H ≤ φ₂` on `[-9/10, 1)`. -/
theorem H_le {t : ℝ} (h0 : (-9 / 10 : ℝ) ≤ t) (h1 : t < 1) : peval H t / Hd ≤ phi2 t :=
  class_le_one H Hd Q Qd D ps (-368640) (by decide) (by decide) (by decide) id ch
    (by rw [D_eq]; push_cast; linarith) h1

end Case1

end Riesz2.Minor
