/-
Riesz2/MinorS9998.lean — slab [-99/100, -49/50] minorants H_A ≤ φ₂ on the closed slab, H_B, H_C ≤ φ₂ on [lo, 1)
Generated by lean/gen_riesz2/gen_minor2.py; every Bool check was simulated exactly. Do not edit.
-/
import Riesz2.MinorCore

namespace Riesz2.Minor

namespace S9998

def D : ℕ := 409600
theorem D_eq : D = 409600 := rfl

def HA : List ℤ := [491574496266138176, 157404863487081216, -539996326747322496, 424526746487341824, 196315514986655008, -464654977015086848, 504570953625202880, 469139169246593408, -99484885395722400, -42757349427048816, 8880856125735081]
def HAd : ℕ := 72057594037927936
def QA : List ℤ := [-455545699247174208, 334169632779056960, 697401190234403712, -964523073234664320, 228211231500686816, 660970492001741856, -969225930640289728, 35431784378609472, 568624054642315808, -56727535968673584, -51638205552783897, 8880856125735081]
def QAd : ℕ := 36028797018963968
def psA : List (ℤ × ℤ) := [(-405504, -401407)]
theorem idA : gapId HA HAd [1] QA QAd = true := by decide +kernel
theorem chA : posChainOK QA D psA (-405504) (-401407) = true := by decide +kernel
/-- class A: `H ≤ φ₂` on the closed `[-99/100, -49/50]`. -/
theorem HA_le {t : ℝ} (h0 : (-99 / 100 : ℝ) ≤ t) (h1 : t ≤ (-49 / 50 : ℝ)) : peval HA t / HAd ≤ phi2 t :=
  class_le HA HAd QA QAd D psA (-405504) (-401407) (by decide) (by decide) (by decide) (by decide) idA chA
    (by rw [D_eq]; push_cast; linarith) (by rw [D_eq]; push_cast; linarith)

def HB : List ℤ := [4503588003232761, 4503720710023640, 4502385333955933, 4496066316525126, 4562842097558524, 4725354337912522, 3730439341451168, 1603270506537556, 5698903711106732, 13609698776954688, 8220815774319569]
def HBd : ℕ := 9007199254740992
def QB : List ℤ := [11624137735, -132706790879, 1335376067707, 6319017430807, -66775781033398, -162512240353998, 994914996461354, 2127168834913612, -4095633204569176, -7910795065847956, 5388883002635119, 8220815774319569]
def QBd : ℕ := 4503599627370496
def psB : List (ℤ × ℤ) := [(-405504, -201728), (-201728, -163520), (-163520, -91880), (-91880, 33490), (33490, 80503), (80503, 245051), (245051, 265619), (265619, 409600)]
theorem idB : gapId HB HBd [1] QB QBd = true := by decide +kernel
theorem chB : posChainOK QB D psB (-405504) (409600) = true := by decide +kernel
/-- class B: `H ≤ φ₂` on `[-99/100, 1)`. -/
theorem HB_le {t : ℝ} (h0 : (-99 / 100 : ℝ) ≤ t) (h1 : t < 1) : peval HB t / HBd ≤ phi2 t :=
  class_le_one HB HBd QB QBd D psB (-405504) (by decide) (by decide) (by decide) idB chB
    (by rw [D_eq]; push_cast; linarith) h1

def HC : List ℤ := [4503515817110503, 4501886936503500, 4497796381647751, 4568007353287872, 4644733315270292, 3969309763478346, 3141745320233916, 5370950830640500, 8958301769453000, 7297703644952907, 2213779124850155]
def HCd : ℕ := 9007199254740992
def QC : List ℤ := [83810259993, 1628880607003, 4090554855749, -70210971640121, -76725961982420, 675423551791946, 827564443244430, -2229205510406584, -3587350938812500, 1660598124500093, 5083924520102752, 2213779124850155]
def QCd : ℕ := 4503599627370496
def psC : List (ℤ × ℤ) := [(-405504, -354560), (-354560, -306800), (-306800, -217250), (-217250, -60538), (-60538, -1771), (-1771, 101071), (101071, 139637), (139637, 207127), (207127, 232436), (232436, 409600)]
theorem idC : gapId HC HCd [1] QC QCd = true := by decide +kernel
theorem chC : posChainOK QC D psC (-405504) (409600) = true := by decide +kernel
/-- class C: `H ≤ φ₂` on `[-99/100, 1)`. -/
theorem HC_le {t : ℝ} (h0 : (-99 / 100 : ℝ) ≤ t) (h1 : t < 1) : peval HC t / HCd ≤ phi2 t :=
  class_le_one HC HCd QC QCd D psC (-405504) (by decide) (by decide) (by decide) idC chC
    (by rw [D_eq]; push_cast; linarith) h1

end S9998

end Riesz2.Minor
