/-
Riesz2/MinorS9896.lean — slab [-49/50, -24/25] minorants H_A ≤ φ₂ on the closed slab, H_B, H_C ≤ φ₂ on [lo, 1)
Generated by lean/gen_riesz2/gen_minor2.py; every Bool check was simulated exactly. Do not edit.
-/
import Riesz2.MinorCore

namespace Riesz2.Minor

namespace S9896

def D : ℕ := 409600
theorem D_eq : D = 409600 := rfl

def HA : List ℤ := [53864706877811152, 47952952470078944, -84053070676292928, -27737194778379508, 91863446728535808, 1954489537745476, 2479275567909860, 57939709542869008, 9655055936744116, 4083259718478471, 12667156858898894]
def HAd : ℕ := 9007199254740992
def QA : List ℤ := [-49361107250440656, 5911754407732208, 132006023146371872, -56315875897913420, -119600641506915316, 89908957190790332, -524786030164384, -55460433974959148, 48284653606124892, 5571796218265645, -8583897140420423, 12667156858898894]
def QAd : ℕ := 4503599627370496
def psA : List (ℤ × ℤ) := [(-401408, -393215)]
theorem idA : gapId HA HAd [1] QA QAd = true := by decide +kernel
theorem chA : posChainOK QA D psA (-401408) (-393215) = true := by decide +kernel
/-- class A: `H ≤ φ₂` on the closed `[-49/50, -24/25]`. -/
theorem HA_le {t : ℝ} (h0 : (-49 / 50 : ℝ) ≤ t) (h1 : t ≤ (-24 / 25 : ℝ)) : peval HA t / HAd ≤ phi2 t :=
  class_le HA HAd QA QAd D psA (-401408) (-393215) (by decide) (by decide) (by decide) (by decide) idA chA
    (by rw [D_eq]; push_cast; linarith) (by rw [D_eq]; push_cast; linarith)

def HB : List ℤ := [4503579125066664, 4504096360685706, 4498805752332326, 4482124832447520, 4679968961632588, 5008815909221268, 2728517245914016, -1020914887430578, 6408352010257659, 18264072054424232, 10728652666575634]
def HBd : ℕ := 9007199254740992
def QB : List ℤ := [20502303832, -517235619042, 5290608353380, 16680919884806, -197844129185068, -328846947588680, 2280298663307252, 3749432133344594, -7429266897688237, -11855720044166573, 7535419387848598, 10728652666575634]
def QBd : ℕ := 4503599627370496
def psB : List (ℤ × ℤ) := [(-401408, -300032), (-300032, -211328), (-211328, -133712), (-133712, 2116), (2116, 53051), (53051, 97619), (97619, 253609), (253609, 273107), (273107, 281637), (281637, 409600)]
theorem idB : gapId HB HBd [1] QB QBd = true := by decide +kernel
theorem chB : posChainOK QB D psB (-401408) (409600) = true := by decide +kernel
/-- class B: `H ≤ φ₂` on `[-49/50, 1)`. -/
theorem HB_le {t : ℝ} (h0 : (-49 / 50 : ℝ) ≤ t) (h1 : t < 1) : peval HB t / HBd ≤ phi2 t :=
  class_le_one HB HBd QB QBd D psB (-401408) (by decide) (by decide) (by decide) idB chB
    (by rw [D_eq]; push_cast; linarith) h1

def HC : List ℤ := [9006939666073152, 9002955847362626, 8999468878067320, 9151499299890900, 9308628430813520, 7820558614078804, 5746407707693024, 10406931337725588, 19078033852265400, 16438881466999418, 5186253752454259]
def HCd : ℕ := 18014398509481984
def QC : List ℤ := [259588667840, 3983818710526, 3486969295306, -152030421823580, -157129130922620, 1488069816734716, 2074150906385780, -4660523630032564, -8671102514539812, 2639152385265982, 11252627714545159, 5186253752454259]
def QCd : ℕ := 9007199254740992
def psC : List (ℤ × ℤ) := [(-401408, -350720), (-350720, -303200), (-303200, -214100), (-214100, -58175), (-58175, 296), (296, 102622), (102622, 140994), (140994, 208145), (208145, 233326), (233326, 244343), (244343, 409600)]
theorem idC : gapId HC HCd [1] QC QCd = true := by decide +kernel
theorem chC : posChainOK QC D psC (-401408) (409600) = true := by decide +kernel
/-- class C: `H ≤ φ₂` on `[-49/50, 1)`. -/
theorem HC_le {t : ℝ} (h0 : (-49 / 50 : ℝ) ≤ t) (h1 : t < 1) : peval HC t / HCd ≤ phi2 t :=
  class_le_one HC HCd QC QCd D psC (-401408) (by decide) (by decide) (by decide) idC chC
    (by rw [D_eq]; push_cast; linarith) h1

end S9896

end Riesz2.Minor
