/-
Riesz2/MinorS9493.lean — slab [-47/50, -93/100] minorants H_A ≤ φ₂ on the closed slab, H_B, H_C ≤ φ₂ on [lo, 1)
Generated by lean/gen_riesz2/gen_minor2.py; every Bool check was simulated exactly. Do not edit.
-/
import Riesz2.MinorCore

namespace Riesz2.Minor

namespace S9493

def D : ℕ := 409600
theorem D_eq : D = 409600 := rfl

def HA : List ℤ := [114014674701076704, 129092083405984736, -127255732690530816, -78075373286055232, 120045564461377568, -5544028704764544, 10332746605253912, 97291733566783936, 14411517214840838, -10623358036963664, 5322621391206615]
def HAd : ℕ := 18014398509481984
def QA : List ℤ := [-105007475446335712, -15077408704908032, 256347816096515552, -49180359404475584, -198120937747432800, 125589593166142112, -15876775310018456, -86958986961530024, 82880216351943098, 25034875251804502, -15945979428170279, 5322621391206615]
def QAd : ℕ := 9007199254740992
def psA : List (ℤ × ℤ) := [(-385024, -380927)]
theorem idA : gapId HA HAd [1] QA QAd = true := by decide +kernel
theorem chA : posChainOK QA D psA (-385024) (-380927) = true := by decide +kernel
/-- class A: `H ≤ φ₂` on the closed `[-47/50, -93/100]`. -/
theorem HA_le {t : ℝ} (h0 : (-47 / 50 : ℝ) ≤ t) (h1 : t ≤ (-93 / 100 : ℝ)) : peval HA t / HAd ≤ phi2 t :=
  class_le HA HAd QA QAd D psA (-385024) (-380927) (by decide) (by decide) (by decide) (by decide) idA chA
    (by rw [D_eq]; push_cast; linarith) (by rw [D_eq]; push_cast; linarith)

def HB : List ℤ := [4503565468328616, 4504605307427977, 4494117577774418, 4477993732936712, 4768981941028259, 4969507827174324, 2268689046628512, -158429016760751, 8131886154717110, 16510305865333492, 8465868510578829]
def HBd : ℕ := 9007199254740992
def QB : List ℤ := [34159041880, -1039839099361, 10487729653559, 16123844837706, -290988208091547, -200525886146065, 2700818780545812, 2427118063389263, -8290315171477861, -8378419710616382, 8044437354754663, 8465868510578829]
def QBd : ℕ := 4503599627370496
def psB : List (ℤ × ℤ) := [(-385024, -285696), (-285696, -242240), (-242240, -160760), (-160760, -89465), (-89465, -27082), (-27082, 27503), (27503, 75265), (75265, 117056), (117056, 263328), (263328, 272470), (272470, 289611), (289611, 409600)]
theorem idB : gapId HB HBd [1] QB QBd = true := by decide +kernel
theorem chB : posChainOK QB D psB (-385024) (409600) = true := by decide +kernel
/-- class B: `H ≤ φ₂` on `[-47/50, 1)`. -/
theorem HB_le {t : ℝ} (h0 : (-47 / 50 : ℝ) ≤ t) (h1 : t < 1) : peval HB t / HBd ≤ phi2 t :=
  class_le_one HB HBd QB QBd D psB (-385024) (by decide) (by decide) (by decide) idB chB
    (by rw [D_eq]; push_cast; linarith) h1

def HC : List ℤ := [9007139071643152, 9006108775777422, 9002749540871040, 9055805492485794, 9158913718651602, 8505483796684772, 7235854914725182, 9787783301555324, 15755397802729498, 14069341932020166, 4776443473675611]
def HCd : ℕ := 18014398509481984
def QC : List ℤ := [60183097840, 1030295865730, 3359234906382, -53055951614754, -103108226165808, 653429921966830, 1269628881959590, -2551928386830142, -5967614501174174, 1686055870709332, 9292898458344555, 4776443473675611]
def QCd : ℕ := 9007199254740992
def psC : List (ℤ × ℤ) := [(-385024, -335360), (-335360, -288800), (-288800, -201500), (-201500, -48725), (-48725, 65856), (65856, 108824), (108824, 184018), (184018, 212215), (212215, 409600)]
theorem idC : gapId HC HCd [1] QC QCd = true := by decide +kernel
theorem chC : posChainOK QC D psC (-385024) (409600) = true := by decide +kernel
/-- class C: `H ≤ φ₂` on `[-47/50, 1)`. -/
theorem HC_le {t : ℝ} (h0 : (-47 / 50 : ℝ) ≤ t) (h1 : t < 1) : peval HC t / HCd ≤ phi2 t :=
  class_le_one HC HCd QC QCd D psC (-385024) (by decide) (by decide) (by decide) idC chC
    (by rw [D_eq]; push_cast; linarith) h1

end S9493

end Riesz2.Minor
