/-
Riesz2/MinorS9694.lean — slab [-24/25, -47/50] minorants H_A ≤ φ₂ on the closed slab, H_B, H_C ≤ φ₂ on [lo, 1)
Generated by lean/gen_riesz2/gen_minor2.py; every Bool check was simulated exactly. Do not edit.
-/
import Riesz2.MinorCore

namespace Riesz2.Minor

namespace S9694

def D : ℕ := 409600
theorem D_eq : D = 409600 := rfl

def HA : List ℤ := [42101709260114224, 62503219016166728, -50000809441544664, -64403241015493472, 71924307600150920, 26667936913880672, -18707117625794260, 54637128663005088, 21347262227293976, -7782512372705455, 7319705185603268]
def HAd : ℕ := 9007199254740992
def QA : List ℤ := [-37598109632743728, -20401509756052504, 112504028457711392, 14402431573948808, -136327548615644392, 45256370686270248, 45375054539674932, -73344246288799348, 33289866435711112, 29129774599999431, -15102217558308723, 7319705185603268]
def QAd : ℕ := 4503599627370496
def psA : List (ℤ × ℤ) := [(-393216, -385023)]
theorem idA : gapId HA HAd [1] QA QAd = true := by decide +kernel
theorem chA : posChainOK QA D psA (-393216) (-385023) = true := by decide +kernel
/-- class A: `H ≤ φ₂` on the closed `[-24/25, -47/50]`. -/
theorem HA_le {t : ℝ} (h0 : (-24 / 25 : ℝ) ≤ t) (h1 : t ≤ (-47 / 50 : ℝ)) : peval HA t / HAd ≤ phi2 t :=
  class_le HA HAd QA QAd D psA (-393216) (-385023) (by decide) (by decide) (by decide) (by decide) idA chA
    (by rw [D_eq]; push_cast; linarith) (by rw [D_eq]; push_cast; linarith)

def HB : List ℤ := [4503563362662502, 4504666883840448, 4493930083274134, 4471699448648992, 4791146992108745, 5119744742748530, 2031490391892564, -1587439942677632, 7661976676365016, 18974425280346256, 10331177629976512]
def HBd : ℕ := 9007199254740992
def QB : List ℤ := [36264707994, -1103521177946, 10736800566314, 22230634625142, -319447543459753, -328597750639785, 3088254350855966, 3618930334570196, -9249416619042648, -11312448603981240, 8643247650369744, 10331177629976512]
def QBd : ℕ := 4503599627370496
def psB : List (ℤ × ℤ) := [(-393216, -292864), (-292864, -248960), (-248960, -228380), (-228380, -148633), (-148633, -9075), (-9075, 43259), (43259, 89051), (89051, 129119), (129119, 269359), (269359, 286889), (286889, 409600)]
theorem idB : gapId HB HBd [1] QB QBd = true := by decide +kernel
theorem chB : posChainOK QB D psB (-393216) (409600) = true := by decide +kernel
/-- class B: `H ≤ φ₂` on `[-24/25, 1)`. -/
theorem HB_le {t : ℝ} (h0 : (-24 / 25 : ℝ) ≤ t) (h1 : t < 1) : peval HB t / HBd ≤ phi2 t :=
  class_le_one HB HBd QB QBd D psB (-393216) (by decide) (by decide) (by decide) idB chB
    (by rw [D_eq]; push_cast; linarith) h1

def HC : List ℤ := [9007052990949352, 9005038759394464, 9004444800750500, 9090278262220424, 9161535073881736, 8200076506917054, 6971967465415384, 10522844875387508, 16705472977788878, 13931037156912150, 4405082215907949]
def HCd : ℕ := 18014398509481984
def QC : List ℤ := [146263791640, 2014231554888, 593958643964, -85833461469924, -71256811661312, 961458566964682, 1228109041501670, -3550877409972124, -6182628102401370, 2774435820876728, 9525954941004201, 4405082215907949]
def QCd : ℕ := 9007199254740992
def psC : List (ℤ × ℤ) := [(-393216, -343040), (-343040, -296000), (-296000, -207800), (-207800, -53450), (-53450, 62312), (62312, 105723), (105723, 181692), (181692, 210180), (210180, 260035), (260035, 409600)]
theorem idC : gapId HC HCd [1] QC QCd = true := by decide +kernel
theorem chC : posChainOK QC D psC (-393216) (409600) = true := by decide +kernel
/-- class C: `H ≤ φ₂` on `[-24/25, 1)`. -/
theorem HC_le {t : ℝ} (h0 : (-24 / 25 : ℝ) ≤ t) (h1 : t < 1) : peval HC t / HCd ≤ phi2 t :=
  class_le_one HC HCd QC QCd D psC (-393216) (by decide) (by decide) (by decide) idC chC
    (by rw [D_eq]; push_cast; linarith) h1

end S9694

end Riesz2.Minor
