/-
Riesz2/MinorCap.lean — sharp cap minorants, exact contact at -1 (A), 0 (B), roots of 4t²+2t-1 (C)
Generated by lean/gen_riesz2/gen_minor2.py; every Bool check was simulated exactly. Do not edit.
-/
import Riesz2.MinorCore

namespace Riesz2.Minor

namespace Cap

def D : ℕ := 409600
theorem D_eq : D = 409600 := rfl

def HA : List ℤ := [5120483140960, 3988959052081, -4880253269159, 817068191284, 1684212577742, -6613665650589, -5803699155541, -8670773691745, 1449455089248, 16712295681240, 5818116453960, -6424374864402, -3303928212397]
def HAd : ℕ := 1099511627776
def QA : List ℤ := [-4570727327072, 5702251415951, 3166960905289, -8864282365732, 7997137979274, 300740249057, -1110706744105, 3977781280309, -14098010061302, -1164830530690, 12059009757970, 183481560392, -3303928212397]
def QAd : ℕ := 549755813888
def psA : List (ℤ × ℤ) := [(-409600, -405503)]
theorem idA : gapId HA HAd [1, 1] QA QAd = true := by decide +kernel
theorem chA : posChainOK QA D psA (-409600) (-405503) = true := by decide +kernel
/-- cap class A: `H_A ≤ φ₂` on `[-1, -99/100]`, equality only at `-1`. -/
theorem capA {t : ℝ} (h0 : -1 ≤ t) (h1 : t ≤ (-99 / 100 : ℝ)) :
    peval HA t / HAd ≤ phi2 t ∧ (peval HA t / HAd = phi2 t → t = -1) :=
  capA_of HA HAd QA QAd D psA (-405503) (by decide) (by decide) (by decide) (by decide) idA chA h0
    (by rw [D_eq]; push_cast; linarith)

def HB : List ℤ := [549755813888, 549755813888, 549755813888, 549755813888, 545996989756, 543117448977, 525216535739, 881469599515, 1937113307541, -2649364572953, -9191636818208, 6634155720279, 11866604820195]
def HBd : ℕ := 1099511627776
def QB : List ℤ := [3758824132, 2879540779, 17900913238, -356253063776, -1055643708026, 4586477880494, 6542272245255, -15825792538487, -5232449099916, 11866604820195]
def QBd : ℕ := 549755813888
def psB : List (ℤ × ℤ) := [(-409600, -204800), (-204800, -166400), (-166400, -157400), (-157400, -152971), (-152971, -12329), (-12329, 93153), (93153, 172264), (172264, 290932), (290932, 350266), (350266, 409600)]
theorem idB : gapId HB HBd [0, 0, 0, 0, 1] QB QBd = true := by decide +kernel
theorem chB : posChainOK QB D psB (-409600) (409600) = true := by decide +kernel
/-- cap class B: `H_B ≤ φ₂` on `[-1, 1)`, equality only at `0`. -/
theorem capB {t : ℝ} (h0 : -1 ≤ t) (h1 : t < 1) :
    peval HB t / HBd ≤ phi2 t ∧ (peval HB t / HBd = phi2 t → t = 0) :=
  capB_of HB HBd QB QBd D psB (by decide) (by decide) (by decide) idB chB h0 h1

def HC : List ℤ := [28141590018443127, 28236062814183668, 27988154327712314, 26132612028313600, 30781975081206616, 49172958289305600, 28578915680972800, -64889974645555200, -76719092204032000, 90468238253568000, 211513843399321600, 138610750382233600, 31518521610291200]
def HCd : ℕ := 56294995342131200
def QC : List ℤ := [5907652622473, -70842185250649, -11829644041350, 1430332540271150, 2063601054077000, -3092499562034400, -6217597763173600, 325563516125600, 4723356697603200, 1969907600643200]
def QCd : ℕ := 28147497671065600
def psC : List (ℤ × ℤ) := [(-409600, -204800), (-204800, -185600), (-185600, -36800), (-36800, 19000), (19000, 43412), (43412, 54855), (54855, 232227), (232227, 320913), (320913, 331998), (331998, 409600)]
theorem idC : gapId HC HCd [1, -4, -4, 16, 16] QC QCd = true := by decide +kernel
theorem chC : posChainOK QC D psC (-409600) (409600) = true := by decide +kernel
/-- cap class C: `H_C ≤ φ₂` on `[-1, 1)`, equality only at the roots of `4t²+2t-1`. -/
theorem capC {t : ℝ} (h0 : -1 ≤ t) (h1 : t < 1) :
    peval HC t / HCd ≤ phi2 t ∧ (peval HC t / HCd = phi2 t → 4 * t ^ 2 + 2 * t - 1 = 0) :=
  capC_of HC HCd QC QCd D psC (by decide) (by decide) (by decide) idC chC h0 h1

end Cap

end Riesz2.Minor
