import CoulN7.S9390.ChkMeta
import CoulN7.S9390.ChkA
import CoulN7.S9390.ChkB
import CoulN7.S9390.ChkG
import CoulN7.Bridge
import CoulN7.Minor.S9390
/-! Slab S9390: `ThomsonGen.SlabSpec φ₁ (-93 / 100 : ℝ) (-9 / 10 : ℝ)` (Coulomb) from the checked packed certificate `tc_s9390` and
the minorants of `CoulN7.Minor.MS9390` (identified through `scaledEq`).
Generated by `numerics/n7_interval/lean/gen/gen_spec1.py`; do not edit. -/

open Real
namespace CoulN7
namespace S9390
open ThomsonN7 ThomsonN7.Cert ThomsonGen

theorem e_eq : tc_s9390.e = 266610559930686373888 := rfl
theorem lam_eq : tc_s9390.Lam = 18446744073709551616 := rfl
theorem an_eq : tc_s9390.an = -93 := rfl
theorem ad_eq : tc_s9390.ad = 100 := rfl
theorem bn_eq : tc_s9390.bn = -9 := rfl
theorem bd_eq : tc_s9390.bd = 10 := rfl
theorem lam_pos : 0 < tc_s9390.Lam := by rw [lam_eq]; norm_num
theorem alo_eq : tc_s9390.alo = (-93 / 100 : ℝ) := by
  unfold TCert.alo; rw [an_eq, ad_eq]; norm_num
theorem ahi_eq : tc_s9390.ahi = (-9 / 10 : ℝ) := by
  unfold TCert.ahi; rw [bn_eq, bd_eq]; norm_num
/-- `E(P) < ef` (margin 1.000e-05). -/
theorem ef_gt : pairEnergy ThomsonN7.Base.phi pentBipyramid < tc_s9390.ef := by
  refine lt_of_le_of_lt pairEnergy_pent_le ?_
  unfold TCert.ef; rw [e_eq, lam_eq]; norm_num
theorem eA : scaledEq CoulN7.Minor.MS9390.HAd tc_s9390.HA tc_s9390.Lam CoulN7.Minor.MS9390.HA = true := by decide +kernel
theorem eB : scaledEq CoulN7.Minor.MS9390.HBd tc_s9390.HB tc_s9390.Lam CoulN7.Minor.MS9390.HB = true := by decide +kernel
theorem eC : scaledEq CoulN7.Minor.MS9390.HCd tc_s9390.HC tc_s9390.Lam CoulN7.Minor.MS9390.HC = true := by decide +kernel

/-- **Slab S9390.** -/
theorem spec : SlabSpec ThomsonN7.Base.phi (-93 / 100 : ℝ) (-9 / 10 : ℝ) :=
  slabSpec_of_minor tc_s9390 tc_s9390_meta tc_s9390_A tc_s9390_B tc_s9390_G alo_eq ahi_eq ef_gt lam_pos
    (by decide) (by decide) (by decide) eA eB eC
    (fun t h1 h2 => CoulN7.Minor.MS9390.HA_le t h1 h2) (fun t h1 h2 => CoulN7.Minor.MS9390.HB_le t h1 h2)
    (fun t h1 h2 => CoulN7.Minor.MS9390.HC_le t h1 h2)

end S9390
end CoulN7
