#!/usr/bin/env python3
"""Spec modules of the log port: LogN7/<Slab>/Spec.lean (SlabSpec φ₀) and LogN7/Cap/Spec.lean (CapSpec φ₀ (1/1650)).

usage (worktree root): python3 lean/gen_log/gen_spec_log.py
Reads the emitted certificate data (emit_tcert.py parse / parse_n) and the minorant modules LogN7/Minor/*.lean.
"""
import os
import re
import sys
from fractions import Fraction as Fr

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import emit_tcert as et  # noqa: E402

LEAN = os.path.normpath(os.path.join(HERE, ".."))
L2, L5 = 69314718055994530941723212145717, 160943791243410037460075933322218
EPU = -(Fr(6 * L2) + Fr(5, 2) * L5) / 10 ** 32
SLABS = [("S9998", "Slab9998"), ("S9896", "Slab9896"), ("S9694", "Slab9694"), ("S9493", "Slab9493"),
         ("S9390", "Slab9390")]


def q(x):
    x = Fr(x)
    return f"({x.numerator} / {x.denominator} : ℝ)" if x.denominator != 1 else f"({x.numerator} : ℝ)"


def minor_ranges(path):
    s = open(path).read()
    out = {}
    for k in "ABC":
        m = re.search(rf"theorem H{k}_le_phi \{{t : ℝ\}} \(h0 : \(\((-?\d+) : ℤ\) : ℝ\) ≤ D \* t\) \(h1 : (.*?)\) :", s)
        out[k] = (int(m.group(1)), m.group(2))
    D = int(re.search(r"def D : ℕ := (\d+)", s).group(1))
    return out, D


def slab(name, mname):
    tc, _ = et.parse(os.path.join(LEAN, "LogN7", name), name)
    nm = "tc_" + name.lower()
    M = f"LogLean.Minor.Cell{mname}"
    rng, D = minor_ranges(os.path.join(LEAN, "LogN7", "Minor", f"Minor{mname}.lean"))
    lo, hi = Fr(tc.an, tc.ad), Fr(tc.bn, tc.bd)
    ef = Fr(tc.e, tc.Lam)
    assert EPU < ef, (name, float(ef - EPU))
    for k in "ABC":
        assert Fr(rng[k][0], D) <= lo, (name, k)
    rA = int(re.search(r"theorem HA_le_phi .*?\(h1 : \(D : ℝ\) \* t < \(\((-?\d+) : ℤ\) : ℝ\)\)",
                       open(os.path.join(LEAN, "LogN7", "Minor", f"Minor{mname}.lean")).read()).group(1))
    assert hi * D < rA
    h1A = "(by rw [hD]; push_cast; linarith)"
    txt = f"""import LogN7.{name}.ChkMeta
import LogN7.{name}.ChkA
import LogN7.{name}.ChkB
import LogN7.{name}.ChkG
import LogN7.Bridge
import LogN7.Minor.Minor{mname}
/-! Slab {name}: `ThomsonGen.SlabSpec φ₀ {lo} {hi}` from the checked packed certificate `{nm}` and the 1-D
minorants of `{M}` (identified through `scaledEq`).  Generated by lean/gen_log/gen_spec_log.py; do not edit. -/

open Real
namespace LogN7
namespace {name}
open ThomsonN7 ThomsonN7.Cert ThomsonGen

theorem e_eq : {nm}.e = {tc.e} := rfl
theorem lam_eq : {nm}.Lam = {tc.Lam} := rfl
theorem an_eq : {nm}.an = {tc.an} := rfl
theorem ad_eq : {nm}.ad = {tc.ad} := rfl
theorem bn_eq : {nm}.bn = {tc.bn} := rfl
theorem bd_eq : {nm}.bd = {tc.bd} := rfl
theorem lam_pos : 0 < {nm}.Lam := by rw [lam_eq]; norm_num
theorem alo_eq : {nm}.alo = {q(lo)} := by
  unfold TCert.alo; rw [an_eq, ad_eq]; norm_num
theorem ahi_eq : {nm}.ahi = {q(hi)} := by
  unfold TCert.ahi; rw [bn_eq, bd_eq]; norm_num
/-- `E(P) < ef` (margin {float(ef - EPU):.3e}). -/
theorem ef_gt : pairEnergy LogLean.Minor.phi pentBipyramid < {nm}.ef := by
  refine lt_of_le_of_lt pairEnergy_pent_le ?_
  unfold TCert.ef; rw [e_eq, lam_eq]; norm_num
theorem eA : scaledEq {M}.HdA {nm}.HA {nm}.Lam {M}.HA = true := by decide +kernel
theorem eB : scaledEq {M}.HdB {nm}.HB {nm}.Lam {M}.HB = true := by decide +kernel
theorem eC : scaledEq {M}.HdC {nm}.HC {nm}.Lam {M}.HC = true := by decide +kernel
theorem hD : ({M}.D : ℝ) = {D} := by norm_num [{M}.D]

/-- **Slab {name}.** -/
theorem spec : SlabSpec LogLean.Minor.phi {q(lo)} {q(hi)} :=
  slabSpec_of_minor {nm} {nm}_meta {nm}_A {nm}_B {nm}_G alo_eq ahi_eq ef_gt lam_pos
    (by decide) (by decide) (by decide) eA eB eC
    (fun t h1 h2 => {M}.HA_le_phi (by rw [hD]; push_cast; linarith) {h1A})
    (fun t h1 h2 => {M}.HB_le_phi (by rw [hD]; push_cast; linarith) h2)
    (fun t h1 h2 => {M}.HC_le_phi (by rw [hD]; push_cast; linarith) h2)

end {name}
end LogN7
"""
    open(os.path.join(LEAN, "LogN7", name, "Spec.lean"), "w").write(txt)
    return float(ef - EPU)


def cap():
    tcn, _ = et.parse_n(os.path.join(LEAN, "LogN7", "Cap"), "Cap")
    tc = tcn.toTCert()
    nm = "tc_cap"
    M = "LogLean.Minor.Cap"
    ef = Fr(tc.e, tc.Lam)
    assert EPU <= ef + Fr(1, 10 ** 16), float(EPU - ef)
    assert (tc.an, tc.ad) == (-1, 1) and Fr(tc.bn, tc.bd) == Fr(-99, 100)
    txt = f"""import LogN7.Cap.ChkMeta
import LogN7.Cap.ChkA
import LogN7.Cap.ChkB
import LogN7.Cap.ChkG
import LogN7.Bridge
import LogN7.Minor.MinorCap
/-! Cap: `ThomsonGen.CapSpec φ₀ (1/1650) (-99/100)` (checklist item 4) from the checked facially reduced
certificate `{nm}` (`Cert.TCertN`, re-rounded, NOT exactly sharp: E(P) − ef = {float(EPU - ef):.3e} ≤ δ = 10⁻¹⁶)
and the coercive minorants of `{M}` (identified through `scaledEq`).
Generated by lean/gen_log/gen_spec_log.py; do not edit. -/

open Real
namespace LogN7
namespace Cap
open ThomsonN7 ThomsonN7.Cert ThomsonGen

theorem e_eq : {nm}.toTCert.e = {tc.e} := rfl
theorem lam_eq : {nm}.toTCert.Lam = {tc.Lam} := rfl
theorem an_eq : {nm}.toTCert.an = {tc.an} := rfl
theorem ad_eq : {nm}.toTCert.ad = {tc.ad} := rfl
theorem bn_eq : {nm}.toTCert.bn = {tc.bn} := rfl
theorem bd_eq : {nm}.toTCert.bd = {tc.bd} := rfl
theorem lam_pos : 0 < {nm}.toTCert.Lam := by rw [lam_eq]; norm_num
theorem alo_eq : {nm}.toTCert.alo = -1 := by
  unfold TCert.alo; rw [an_eq, ad_eq]; norm_num
theorem ahi_eq : {nm}.toTCert.ahi = (-99 / 100 : ℝ) := by
  unfold TCert.ahi; rw [bn_eq, bd_eq]; norm_num
/-- `E(P) ≤ ef + δ`, `δ = 10⁻¹⁶`. -/
theorem ef_ge : pairEnergy LogLean.Minor.phi pentBipyramid ≤ {nm}.toTCert.ef + 1 / 10 ^ 16 := by
  refine pairEnergy_pent_le.trans ?_
  unfold TCert.ef; rw [e_eq, lam_eq]; norm_num
theorem eA : scaledEq {M}.HdA {nm}.toTCert.HA {nm}.toTCert.Lam {M}.HA = true := by decide +kernel
theorem eB : scaledEq {M}.HdB {nm}.toTCert.HB {nm}.toTCert.Lam {M}.HB = true := by decide +kernel
theorem eC : scaledEq {M}.HdC {nm}.toTCert.HC {nm}.toTCert.Lam {M}.HC = true := by decide +kernel

/-- **The log cap** (checklist item 4). -/
theorem spec : CapSpec LogLean.Minor.phi (1 / 1650) (-99 / 100 : ℝ) :=
  capSpec_of_minorN {nm} {nm}_meta {nm}_A {nm}_B {nm}_G alo_eq ahi_eq ef_ge lam_pos
    (by decide) (by decide) (by decide) eA eB eC
    (fun t h1 h2 => {M}.capA h1 h2) (fun t h1 h2 => {M}.capB h1 h2)
    (fun t h1 h2 => {M}.capC h1 h2)

end Cap
end LogN7
"""
    open(os.path.join(LEAN, "LogN7", "Cap", "Spec.lean"), "w").write(txt)
    return float(EPU - ef)


if __name__ == "__main__":
    for n, m in SLABS:
        print(n, "margin", slab(n, m))
    print("Cap E(P)-ef", cap())
