#!/usr/bin/env python3
"""Per-declaration kernel checks for the log port (memory: one `decide +kernel` per block).

usage (worktree root, nice -n 19):
  python3 lean/gen_log/gen_split.py <Name>          slab (TCert):  rewrites LogN7/<Name>/ChkMeta.lean, ChkA/B/G.lean
  python3 lean/gen_log/gen_split.py <Name> --tcertn cap (TCertN):  rewrites LogN7/<Name>/ChkA/B/G.lean only
                                                    (checkMeta of a TCertN: gen_capchk.py)

ChkMeta (slabs): `(tc.blkP k).ok (tc.m k)` / `blkR` per k, `okF s.z.length s.B` per SOS block, assembled by
`TCert.checkMeta_of_parts` (ThomsonGen/Cert/Split.lean).
ChkX: `hybW = W`, `hybD = D`, `S.all wf`, `Fx.kev W D = vF`, one `(gT ..).kev W D * fqCur W D s = v_s` per block,
assembled by `hybChk_of_parts` (the literal sum `vF - Σ v_s = 0` is one more `decide`).  W, D, vF, v_s are computed
here by emit_tcert.py's exact simulation of the Lean functions; a wrong value only makes a `decide` fail.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import emit_tcert as et  # noqa: E402

LEAN = os.path.normpath(os.path.join(HERE, ".."))


def head(name, what, imports):
    return ("\n".join(f"import {i}" for i in imports) +
            f"\n/-! {what}\n    Generated by `lean/gen_log/gen_split.py`; do not edit. -/\n\nopen Real\n\n"
            f"section LogN7_{name}_split\nnamespace LogN7\n"
            "open ThomsonN7 ThomsonN7.Kron ThomsonN7.Kron.Ex ThomsonN7.Cert ThomsonN7.ThreePoint\n\n"
            "set_option maxHeartbeats 0\n\n")


def tail(name):
    return f"\nend LogN7\nend LogN7_{name}_split\n"


SIMP_T = "Bool.and_true, Bool.true_and, Bool.and_self"


def chk_module(name, nm, tcx, tc, X, blocks, n):
    """tcx: Lean term of the TCert (tc_s9998 or tc_cap.toTCert); blocks: Lean terms of the TBlks."""
    S = {"A": tc.SA, "B": tc.SB, "G": tc.SG}[X]
    Fx = {"A": tc.FA, "B": tc.FB, "G": tc.FG}[X]()
    bn, bd = (tc.bn, tc.bd) if X == "A" else (1, 1)
    bnL, bdL = (f"{tcx}.bn", f"{tcx}.bd") if X == "A" else ("1", "1")
    info = {}
    assert et.hybChk(Fx, tc.an, tc.ad, bn, bd, S, info), (name, X, info)
    W, D = info["w"], info["D"]
    vF = et.kev(W, D, Fx)
    vs = [et.kev(W, D, et.gT(tc.an, tc.ad, bn, bd, s.g)) * et.fqFlat(W, D, s) for s in S]
    assert vF - sum(vs) == 0
    args = f"{tcx}.F{X} {tcx}.an {tcx}.ad {bnL} {bdL} {tcx}.S{X}"
    L = [f"theorem {nm}_{X}_W : hybW {args} = {W} := by decide +kernel",
         f"theorem {nm}_{X}_D : hybD {args} = {D} := by decide +kernel",
         f"theorem {nm}_{X}_wf : {tcx}.S{X}.all TBlk.wf = true := by decide +kernel",
         f"def {nm}_v{X} : ℤ := {vF}",
         f"theorem {nm}_{X}_F : ({tcx}.F{X}).kev {W} {D} = {nm}_v{X} := by decide +kernel"]
    for i, (b, v) in enumerate(zip(blocks, vs)):
        L.append(f"def {nm}_v{X}{i} : ℤ := {v}")
        L.append(f"theorem {nm}_{X}_s{i} : (gT {tcx}.an {tcx}.ad {bnL} {bdL} ({b}).g).kev {W} {D} * "
                 f"fqCur {W} {D} ({b}) = {nm}_v{X}{i} := by decide +kernel")
    vl = ", ".join(f"{nm}_v{X}{i}" for i in range(len(S)))
    bl = ", ".join(blocks)
    sl = ", ".join(f"{nm}_{X}_s{i}" for i in range(len(S)))
    unf = "TCertN.chk" + X + " TCert.chk" + X if n else "TCert.chk" + X
    L.append(f"""
/-- `chk{X}` from the per-block values (`hybChk_of_parts`). -/
theorem {nm}_{X} : {nm}.chk{X} = true := by
  unfold {unf}
  refine hybChk_of_parts fqCur _ _ _ _ _ _ {W} {D} {nm}_v{X} [{vl}] {nm}_{X}_wf {nm}_{X}_W {nm}_{X}_D {nm}_{X}_F ?_ ?_
  · rw [show {tcx}.S{X} = [{bl}] from rfl]
    simp only [List.map_cons, List.map_nil, {sl}]
  · decide +kernel
""")
    return "\n".join(L), dict(W=W, D=D, vF_bits=abs(vF).bit_length(), nblocks=len(S))


def main():
    name = sys.argv[1]
    tcertn = "--tcertn" in sys.argv
    outdir = os.path.join(LEAN, "LogN7", name)
    nm = "tc_" + name.lower()
    data_mod = f"LogN7.{name}.Data"
    if tcertn:
        tcn, _ = et.parse_n(outdir, name)
        tc = tcn.toTCert()
        tcx = f"{nm}.toTCert"
        blk = {X: [f"{nm}_S{X}{i}.toTBlk" for i in range(len(getattr(tcn, 'S' + X)))] for X in "ABG"}
    else:
        tc, _ = et.parse(outdir, name)
        tcx = nm
        blk = {X: [f"{nm}_S{X}{i}" for i in range(len(getattr(tc, 'S' + X)))] for X in "ABG"}
    rep = {}
    for X in "ABG":
        body, rep[X] = chk_module(name, nm, tcx, tc, X, blk[X], tcertn)
        txt = head(name, f"Kernel check `chk{X}` of `{nm}`, one `decide` per block.",
                   [data_mod, "ThomsonGen.Cert.Split"] + (["ThomsonGen.Cert.NBlk"] if tcertn else [])) + body + tail(name)
        open(os.path.join(outdir, f"Chk{X}.lean"), "w").write(txt)
    if not tcertn:
        info = {}
        assert tc.checkMeta(info), info
        K = tc.dd + 1
        L = []
        for key, fn in (("P", "blkP"), ("R", "blkR")):
            for k in range(K):
                L.append(f"theorem {nm}_m{key}{k} : ({nm}.{fn} {k}).ok ({nm}.m {k}) = true := by decide +kernel")
            hs = ", ".join(f"{nm}_m{key}{k}" for k in range(K))
            L.append(f"theorem {nm}_m{key} : (List.range {nm}.K).all (fun k => ({nm}.{fn} k).ok ({nm}.m k)) = true := by\n"
                     f"  rw [show {nm}.K = {K} from rfl, show List.range {K} = [{', '.join(map(str, range(K)))}] from rfl]\n"
                     f"  simp only [List.all_cons, List.all_nil, {hs}, {SIMP_T}]\n")
        for X in "ABG":
            for i, b in enumerate(blk[X]):
                L.append(f"theorem {nm}_mS{X}{i} : okF ({b}).z.length ({b}).B = true := by decide +kernel")
            hs = ", ".join(f"{nm}_mS{X}{i}" for i in range(len(blk[X])))
            L.append(f"theorem {nm}_mS{X} : {nm}.S{X}.all (fun s => okF s.z.length s.B) = true := by\n"
                     f"  rw [show {nm}.S{X} = [{', '.join(blk[X])}] from rfl]\n"
                     f"  simp only [List.all_cons, List.all_nil, {hs}, {SIMP_T}]\n")
        L.append(f"theorem {nm}_meta : {nm}.checkMeta = true :=\n"
                 f"  TCert.checkMeta_of_parts {nm} (by decide +kernel) (by decide +kernel) (by decide +kernel)\n"
                 f"    (by decide +kernel) (by decide +kernel) (by decide +kernel)\n"
                 f"    {nm}_mP {nm}_mR {nm}_mSA {nm}_mSB {nm}_mSG")
        txt = head(name, f"Kernel check `checkMeta` of `{nm}`, one `decide` per block.",
                   [data_mod, "ThomsonGen.Cert.Split"]) + "\n".join(L) + tail(name)
        open(os.path.join(outdir, "ChkMeta.lean"), "w").write(txt)
    print(name, "split OK", rep)


if __name__ == "__main__":
    main()
