import LogN7.S9998.ChkMeta
import LogN7.S9998.ChkA
import LogN7.S9998.ChkB
import LogN7.S9998.ChkG
import LogN7.Bridge
import LogN7.Minor.MinorSlab9998
/-! Slab S9998: `ThomsonGen.SlabSpec φ₀ -99/100 -49/50` from the checked packed certificate `tc_s9998` and the 1-D
minorants of `LogLean.Minor.CellSlab9998` (identified through `scaledEq`).  Generated by lean/gen_log/gen_spec_log.py; do not edit. -/

open Real
namespace LogN7
namespace S9998
open ThomsonN7 ThomsonN7.Cert ThomsonGen

theorem e_eq : tc_s9998.e = -150936385705394176000 := rfl
theorem lam_eq : tc_s9998.Lam = 18446744073709551616 := rfl
theorem an_eq : tc_s9998.an = -99 := rfl
theorem ad_eq : tc_s9998.ad = 100 := rfl
theorem bn_eq : tc_s9998.bn = -49 := rfl
theorem bd_eq : tc_s9998.bd = 50 := rfl
theorem lam_pos : 0 < tc_s9998.Lam := by rw [lam_eq]; norm_num
theorem alo_eq : tc_s9998.alo = (-99 / 100 : ℝ) := by
  unfold TCert.alo; rw [an_eq, ad_eq]; norm_num
theorem ahi_eq : tc_s9998.ahi = (-49 / 50 : ℝ) := by
  unfold TCert.ahi; rw [bn_eq, bd_eq]; norm_num
/-- `E(P) < ef` (margin 2.000e-04). -/
theorem ef_gt : pairEnergy LogLean.Minor.phi pentBipyramid < tc_s9998.ef := by
  refine lt_of_le_of_lt pairEnergy_pent_le ?_
  unfold TCert.ef; rw [e_eq, lam_eq]; norm_num
theorem eA : scaledEq LogLean.Minor.CellSlab9998.HdA tc_s9998.HA tc_s9998.Lam LogLean.Minor.CellSlab9998.HA = true := by decide +kernel
theorem eB : scaledEq LogLean.Minor.CellSlab9998.HdB tc_s9998.HB tc_s9998.Lam LogLean.Minor.CellSlab9998.HB = true := by decide +kernel
theorem eC : scaledEq LogLean.Minor.CellSlab9998.HdC tc_s9998.HC tc_s9998.Lam LogLean.Minor.CellSlab9998.HC = true := by decide +kernel
theorem hD : (LogLean.Minor.CellSlab9998.D : ℝ) = 409600 := by norm_num [LogLean.Minor.CellSlab9998.D]

/-- **Slab S9998.** -/
theorem spec : SlabSpec LogLean.Minor.phi (-99 / 100 : ℝ) (-49 / 50 : ℝ) :=
  slabSpec_of_minor tc_s9998 tc_s9998_meta tc_s9998_A tc_s9998_B tc_s9998_G alo_eq ahi_eq ef_gt lam_pos
    (by decide) (by decide) (by decide) eA eB eC
    (fun t h1 h2 => LogLean.Minor.CellSlab9998.HA_le_phi (by rw [hD]; push_cast; linarith) (by rw [hD]; push_cast; linarith))
    (fun t h1 h2 => LogLean.Minor.CellSlab9998.HB_le_phi (by rw [hD]; push_cast; linarith) h2)
    (fun t h1 h2 => LogLean.Minor.CellSlab9998.HC_le_phi (by rw [hD]; push_cast; linarith) h2)

end S9998
end LogN7
