import Riesz2.S9390.Data
/-! Kernel check `chkA` of the slab S9390.
    Generated by `lean/gen_riesz2/emit_tcert.py` from `cert_slab_93_90_riesz2.json` (sha256 74514d41a3559a40…).
    Riesz s = 2 kernel `phi2 t = 1/(2-2t)`; format = upstream `TCert` (ThomsonGen/CertT.lean).
    Regenerate; do not edit. -/

open Real

section Riesz2_S9390_tc
namespace Riesz2
open ThomsonN7 ThomsonN7.Kron ThomsonN7.Kron.Ex ThomsonN7.Cert ThomsonN7.ThreePoint

theorem tc_s9390_A : tc_s9390.chkA = true := by decide +kernel

end Riesz2
end Riesz2_S9390_tc
