import Riesz2.S9390.ChkMeta
import Riesz2.S9390.ChkA
import Riesz2.S9390.ChkB
import Riesz2.S9390.ChkG
import Riesz2.Bridge
import Riesz2.MinorS9390
/-! Slab S9390: `ThomsonGen.SlabSpec phi2 -93/100 -9/10` from the checked packed certificate `tc_s9390`
and the 1-D minorants of `Riesz2.Minor.S9390` (identified through `scaledEq`).
Generated by lean/gen_riesz2/gen_spec2.py; do not edit. -/

open Real
namespace Riesz2
namespace S9390
open Minor ThomsonN7.Cert

theorem e_eq : tc_s9390.e = 189080049092726325248 := rfl
theorem lam_eq : tc_s9390.Lam = 18446744073709551616 := rfl
theorem an_eq : tc_s9390.an = -93 := rfl
theorem ad_eq : tc_s9390.ad = 100 := rfl
theorem bn_eq : tc_s9390.bn = -9 := rfl
theorem bd_eq : tc_s9390.bd = 10 := rfl
theorem lam_pos : 0 < tc_s9390.Lam := by rw [lam_eq]; norm_num
theorem alo_eq : tc_s9390.alo = (-93 / 100 : ℝ) := by
  unfold TCert.alo; rw [an_eq, ad_eq]; norm_num
theorem ahi_eq : tc_s9390.ahi = (-9 / 10 : ℝ) := by
  unfold TCert.ahi; rw [bn_eq, bd_eq]; norm_num
theorem ef_gt : (41 / 4 : ℝ) < tc_s9390.ef := by
  unfold TCert.ef; rw [e_eq, lam_eq]; norm_num
theorem eA : scaledEq Minor.S9390.HAd tc_s9390.HA tc_s9390.Lam Minor.S9390.HA = true := by decide +kernel
theorem eB : scaledEq Minor.S9390.HBd tc_s9390.HB tc_s9390.Lam Minor.S9390.HB = true := by decide +kernel
theorem eC : scaledEq Minor.S9390.HCd tc_s9390.HC tc_s9390.Lam Minor.S9390.HC = true := by decide +kernel

/-- **Slab S9390.** -/
theorem spec : ThomsonGen.SlabSpec phi2 (-93 / 100 : ℝ) (-9 / 10 : ℝ) :=
  slabSpec_of_minor tc_s9390 tc_s9390_meta tc_s9390_A tc_s9390_B tc_s9390_G alo_eq ahi_eq ef_gt lam_pos
    (by decide) (by decide) (by decide) eA eB eC
    (fun t h1 h2 => Minor.S9390.HA_le h1 h2) (fun t h1 h2 => Minor.S9390.HB_le h1 h2)
    (fun t h1 h2 => Minor.S9390.HC_le h1 h2)

end S9390
end Riesz2
