import CoulN7.Case1.Data
/-! Coulomb kernel, Case 1: `Blk.ok` of the S-blocks S1..S7, one `decide +kernel` per block.

Generated by `numerics/n7_interval/lean/gen/emit_cert3.py` from `numerics/cells/certs/cert_case1_coulomb_D10.json`
(sha256 a6dedf3d6cf49021985a40ed5e55917aeb2de07a9675ebf867ccbdbd85f1f75c).  Do not edit; regenerate. -/

namespace CoulN7
namespace Case1
open ThomsonN7.Cert ThomsonN7.Cert.Cert3
theorem r2c1_blk_S1 : CoulN7.Case1Data.S1.B.ok CoulN7.Case1Data.S1.z.length = true := by
  decide +kernel

theorem r2c1_blk_S2 : CoulN7.Case1Data.S2.B.ok CoulN7.Case1Data.S2.z.length = true := by
  decide +kernel

theorem r2c1_blk_S3 : CoulN7.Case1Data.S3.B.ok CoulN7.Case1Data.S3.z.length = true := by
  decide +kernel

theorem r2c1_blk_S4 : CoulN7.Case1Data.S4.B.ok CoulN7.Case1Data.S4.z.length = true := by
  decide +kernel

theorem r2c1_blk_S5 : CoulN7.Case1Data.S5.B.ok CoulN7.Case1Data.S5.z.length = true := by
  decide +kernel

theorem r2c1_blk_S6 : CoulN7.Case1Data.S6.B.ok CoulN7.Case1Data.S6.z.length = true := by
  decide +kernel

theorem r2c1_blk_S7 : CoulN7.Case1Data.S7.B.ok CoulN7.Case1Data.S7.z.length = true := by
  decide +kernel
end Case1
end CoulN7
