import CoulN7.Case1.Data
/-! Coulomb kernel, Case 1: `Blk.ok` of the S-block S0.

Generated by `numerics/n7_interval/lean/gen/emit_cert3.py` from `numerics/cells/certs/cert_case1_coulomb_D10.json`
(sha256 a6dedf3d6cf49021985a40ed5e55917aeb2de07a9675ebf867ccbdbd85f1f75c).  Do not edit; regenerate. -/

namespace CoulN7
namespace Case1
open ThomsonN7.Cert ThomsonN7.Cert.Cert3
theorem r2c1_blk_S0 : CoulN7.Case1Data.S0.B.ok CoulN7.Case1Data.S0.z.length = true := by
  decide +kernel
end Case1
end CoulN7
