import CoulN7.Case1.Check
import CoulN7.Bridge
import CoulN7.Minor.Case1
/-! Coulomb kernel, Case 1 claim: `ThomsonGen.Case1Claim φ₁` from the checked cut certificate
(`CoulN7.Case1Data.cf`, `r2c1_cf_ok`) and the minorant `H ≤ φ₁` on `[-9/10, 1)` (`CoulN7.Minor.MCase1.HH_le`, the same rational
polynomial over another denominator: `scaledEq`).  Margin `η = eps/Λ − U ≈ 5.000e-04`, `U ≥ E(P)`
(`pairEnergy_pent_le`).  Generated by `numerics/n7_interval/lean/gen/gen_spec1.py`; do not edit. -/

open Real
namespace CoulN7
namespace Case1
open ThomsonN7 ThomsonN7.Cert ThomsonN7.Cert.Cert3 ThomsonGen

theorem lam_eq : CoulN7.Case1Data.cf.Lam = 498560152080148051525632000 := rfl
theorem eps_eq : CoulN7.Case1Data.cf.eps = 7205927897721177736151040000 := rfl
theorem an_eq : CoulN7.Case1Data.cf.an = -9 := rfl
theorem ad_eq : CoulN7.Case1Data.cf.ad = 10 := rfl
theorem lam_pos : 0 < CoulN7.Case1Data.cf.Lam := by rw [lam_eq]; norm_num

theorem h_scaled : scaledEq CoulN7.Minor.MCase1.HHd CoulN7.Case1Data.cf.h CoulN7.Case1Data.cf.Lam CoulN7.Minor.MCase1.HH = true := by
  decide +kernel

/-- **Case 1 (Coulomb kernel).** -/
theorem claim : Case1Claim ThomsonN7.Base.phi := by
  have hEP := pairEnergy_pent_le
  have hq : ((CoulN7.Case1Data.cf.eps : ℤ) : ℝ) / ((CoulN7.Case1Data.cf.Lam : ℕ) : ℝ) =
      (7205927897721177736151040000 : ℝ) / 498560152080148051525632000 := by
    rw [eps_eq, lam_eq]; push_cast; ring
  have hm : (14452977414221342935044494 : ℝ) / 10 ^ 24 < (7205927897721177736151040000 : ℝ) / 498560152080148051525632000 := by norm_num
  have han : ((CoulN7.Case1Data.cf.an : ℤ) : ℝ) / (CoulN7.Case1Data.cf.ad : ℝ) = -9 / 10 := by
    rw [an_eq, ad_eq]; norm_num
  refine case1Claim_of_cert3 CoulN7.Case1Data.cf r2c1_cf_ok rfl han
    (η := (7205927897721177736151040000 : ℝ) / 498560152080148051525632000 - (14452977414221342935044494 : ℝ) / 10 ^ 24)
    (by linarith) (by rw [hq]; linarith) lam_pos (by decide) h_scaled ?_
  intro t h1 h2
  exact CoulN7.Minor.MCase1.HH_le t h1 h2

end Case1
end CoulN7
