import ThomsonGen.Case1Stat
import CoulN7.Case1.Data
/-! Coulomb kernel, Case 1: statistics machinery for the chunked Kronecker check.

Upstream's `ThomsonN7.Case1.c1Stat` (one structural pass computing `(ℓ¹, deg u, deg v, deg t, kev)`),
`c1Stat_eq`, `c1FtotK` and the composition lemma `c1Stat_idE` (module `ThomsonGen.Case1Stat`) are
data-independent (they import only `Cert3`) and are reused verbatim.  For this certificate the
Kronecker parameters of `Cert.chk` are `w = Nat.log2 ℓ¹ + 1 = 108` and `D = max deg + 1 = 11`.

Generated by `numerics/n7_interval/lean/gen/emit_cert3.py` from `numerics/cells/certs/cert_case1_coulomb_D10.json`
(sha256 a6dedf3d6cf49021985a40ed5e55917aeb2de07a9675ebf867ccbdbd85f1f75c).  Do not edit; regenerate. -/
