import Riesz2.Case1.ChkF
import Riesz2.Case1.ChkS03
import Riesz2.Case1.ChkS47
/-! Riesz s = 2, Case 1: assembly of the chunked check (mirrors upstream `Case1.lean`, first half).
`Riesz2.Case1Data.cf.check = true`: all blocks `Blk.ok`, and `chk cf.idE` with ℓ¹ < 2^109, degrees < 11,
Kronecker value 0 (soundness: `Kron.Ex.ev_eq_zero_of_kev`).

Generated by `lean/gen_riesz2/emit_cert3.py` from `numerics/riesz2/certs/cert_case1_riesz2.json`
(sha256 cb2eb338ee0f7112f07cd9e5be066f2de51439f1043e0b778cfd0d31b513ff0b).  Do not edit; regenerate.

Adapted from huwngtran/thomson-n7-lean @ 25f2fa5, ThomsonN7/Solution.lean (upstream names are
relative to namespace `ThomsonN7`; `ours` ← `upstream`):
* `r2c1_S` ← `Case1.c1_S`; `r2c1_cf_chk` ← `Case1.cf_chk`; `r2c1_cf_blocks` ← `Case1.cf_blocks`;
  `r2c1_cf_sos` ← `Case1.cf_sos`; `r2c1_idE_stat` ← `Case1.c1_idE_stat`.
-/

namespace Riesz2
namespace Case1
open ThomsonN7.Cert ThomsonN7.Cert.Cert3

theorem r2c1_K : Riesz2.Case1Data.cf.K = 4 := rfl

theorem r2c1_S : Riesz2.Case1Data.cf.S = [Riesz2.Case1Data.S0, Riesz2.Case1Data.S1, Riesz2.Case1Data.S2, Riesz2.Case1Data.S3, Riesz2.Case1Data.S4, Riesz2.Case1Data.S5, Riesz2.Case1Data.S6, Riesz2.Case1Data.S7] := rfl

theorem r2c1_range : List.range 4 = [0, 1, 2, 3] := rfl

/-- The statistics of the whole identity expression: `ℓ¹`-norm below `2 ^ 109`, degrees `10, 10, 10`, Kronecker value `0`. -/
theorem r2c1_idE_stat : ThomsonN7.Case1.c1Stat 109 11 Riesz2.Case1Data.cf.idE = (351016231974957654863193710804880, 10, 10, 10, (0 : Int)) := by
  rw [ThomsonN7.Case1.c1Stat_idE, r2c1_K, r2c1_S, r2c1_range]
  simp only [List.map_cons, List.map_nil]
  rw [r2c1_stat_H, r2c1_stat_F0, r2c1_stat_F1, r2c1_stat_F2, r2c1_stat_F3, r2c1_stat_S0, r2c1_stat_S1, r2c1_stat_S2, r2c1_stat_S3, r2c1_stat_S4, r2c1_stat_S5, r2c1_stat_S6, r2c1_stat_S7]
  decide +kernel

/-- The Kronecker check of the identity expression. -/
theorem r2c1_cf_chk : chk Riesz2.Case1Data.cf.idE = true := by
  have h := ThomsonN7.Case1.c1Stat_eq 109 11 Riesz2.Case1Data.cf.idE
  rw [r2c1_idE_stat] at h
  simp only [Prod.mk.injEq] at h
  obtain ⟨hl, hx, hy, hz, hk⟩ := h
  unfold chk
  rw [← hl, ← hx, ← hy, ← hz]
  have hW : Nat.log2 351016231974957654863193710804880 + 1 = 109 := by decide +kernel
  have hD : max 10 (max 10 10) + 1 = 11 := by decide +kernel
  rw [hW, hD]
  exact decide_eq_true hk.symm

/-- The positive-semidefiniteness certificates of the `F`-blocks. -/
theorem r2c1_cf_blocks :
    (List.range Riesz2.Case1Data.cf.K).all
      (fun k => (Riesz2.Case1Data.cf.blk k).ok (Riesz2.Case1Data.cf.m k)) = true := by
  decide +kernel

/-- The positive-semidefiniteness certificates of the `S`-blocks. -/
theorem r2c1_cf_sos : Riesz2.Case1Data.cf.S.all (fun s => s.B.ok s.z.length) = true := by
  decide +kernel

/-- The Case 1 certificate passes upstream's exact check. -/
theorem r2c1_cf_ok : Riesz2.Case1Data.cf.check = true := by
  unfold Cert3.check
  rw [r2c1_cf_chk, r2c1_cf_blocks, r2c1_cf_sos]
  decide +kernel

end Case1
end Riesz2
