import ThomsonGen.Case1Stat
import Riesz2.Case1.Data
/-! Riesz s = 2, Case 1: statistics machinery for the chunked Kronecker check.

Upstream's `ThomsonN7.Case1.c1Stat` (one structural pass computing `(ℓ¹, deg u, deg v, deg t, kev)`),
`c1Stat_eq`, `c1FtotK` and the composition lemma `c1Stat_idE` (module `ThomsonGen.Case1Stat`) are
data-independent (they import only `Cert3`) and are reused verbatim.  For this certificate the
Kronecker parameters of `Cert.chk` are `w = Nat.log2 ℓ¹ + 1 = 109` and `D = max deg + 1 = 11`.

Generated by `lean/gen_riesz2/emit_cert3.py` from `numerics/riesz2/certs/cert_case1_riesz2.json`
(sha256 cb2eb338ee0f7112f07cd9e5be066f2de51439f1043e0b778cfd0d31b513ff0b).  Do not edit; regenerate. -/
