import LogN7.Case1.ChkF
import LogN7.Case1.ChkS0
import LogN7.Case1.ChkS13
import LogN7.Case1.ChkS47
import LogN7.Case1.ChkBF
import LogN7.Case1.ChkBS0
import LogN7.Case1.ChkBS1
/-! Attribution: adapted from huwngtran/thomson-n7-lean @ 25f2fa5, `ThomsonN7/Solution.lean` (ours ← upstream):
`r2c1_S` ← `Case1.c1_S`; `r2c1_cf_chk` ← `Case1.cf_chk`; comments as in `Case1.c1_idE_stat`,
`Case1.cf_blocks`, `Case1.cf_sos`. -/

/-! log kernel, Case 1: assembly of the chunked check (mirrors upstream `Case1.lean`, first half).
`LogN7.Case1Data.cf.check = true`: all blocks `Blk.ok`, and `chk cf.idE` with ℓ¹ < 2^108, degrees < 11,
Kronecker value 0 (soundness: `Kron.Ex.ev_eq_zero_of_kev`).

Generated by `lean/gen_log/emit_cert3.py` from `cert_case1_log_D10.json`
(sha256 d50793adbadf05c191e9c0f39ea08d4739399df89e22598252ed086d63a7b3ae).  Do not edit; regenerate. -/

namespace LogN7
namespace Case1
open ThomsonN7.Cert ThomsonN7.Cert.Cert3

theorem r2c1_K : LogN7.Case1Data.cf.K = 4 := rfl

theorem r2c1_S : LogN7.Case1Data.cf.S = [LogN7.Case1Data.S0, LogN7.Case1Data.S1, LogN7.Case1Data.S2, LogN7.Case1Data.S3, LogN7.Case1Data.S4, LogN7.Case1Data.S5, LogN7.Case1Data.S6, LogN7.Case1Data.S7] := rfl

theorem r2c1_range : List.range 4 = [0, 1, 2, 3] := rfl

/-- The statistics of the whole identity expression: `ℓ¹`-norm below `2 ^ 108`, degrees `10, 10, 10`, Kronecker value `0`. -/
theorem r2c1_idE_stat : ThomsonN7.Case1.c1Stat 108 11 LogN7.Case1Data.cf.idE = (262795887331169832012391330865616, 10, 10, 10, (0 : Int)) := by
  rw [ThomsonN7.Case1.c1Stat_idE, r2c1_K, r2c1_S, r2c1_range]
  simp only [List.map_cons, List.map_nil]
  rw [r2c1_stat_H, r2c1_stat_F0, r2c1_stat_F1, r2c1_stat_F2, r2c1_stat_F3, r2c1_stat_S0, r2c1_stat_S1, r2c1_stat_S2, r2c1_stat_S3, r2c1_stat_S4, r2c1_stat_S5, r2c1_stat_S6, r2c1_stat_S7]
  decide +kernel

/-- The Kronecker check of the identity expression. -/
theorem r2c1_cf_chk : chk LogN7.Case1Data.cf.idE = true := by
  have h := ThomsonN7.Case1.c1Stat_eq 108 11 LogN7.Case1Data.cf.idE
  rw [r2c1_idE_stat] at h
  simp only [Prod.mk.injEq] at h
  obtain ⟨hl, hx, hy, hz, hk⟩ := h
  unfold chk
  rw [← hl, ← hx, ← hy, ← hz]
  have hW : Nat.log2 262795887331169832012391330865616 + 1 = 108 := by decide +kernel
  have hD : max 10 (max 10 10) + 1 = 11 := by decide +kernel
  rw [hW, hD]
  exact decide_eq_true hk.symm

/-- The positive-semidefiniteness certificates of the `F`-blocks (per block: `ChkBF`). -/
theorem r2c1_cf_blocks :
    (List.range LogN7.Case1Data.cf.K).all
      (fun k => (LogN7.Case1Data.cf.blk k).ok (LogN7.Case1Data.cf.m k)) = true := by
  rw [r2c1_K, r2c1_range]; simp only [List.all_cons, List.all_nil, r2c1_blk_F0, r2c1_blk_F1, r2c1_blk_F2, r2c1_blk_F3, Bool.and_self, Bool.and_true]

/-- The positive-semidefiniteness certificates of the `S`-blocks (per block: `ChkBS0`, `ChkBS1`). -/
theorem r2c1_cf_sos : LogN7.Case1Data.cf.S.all (fun s => s.B.ok s.z.length) = true := by
  rw [r2c1_S]; simp only [List.all_cons, List.all_nil, r2c1_blk_S0, r2c1_blk_S1, r2c1_blk_S2, r2c1_blk_S3, r2c1_blk_S4, r2c1_blk_S5, r2c1_blk_S6, r2c1_blk_S7, Bool.and_self, Bool.and_true]

/-- The Case 1 certificate passes upstream's exact check. -/
theorem r2c1_cf_ok : LogN7.Case1Data.cf.check = true := by
  unfold Cert3.check
  rw [r2c1_cf_chk, r2c1_cf_blocks, r2c1_cf_sos]
  decide +kernel

end Case1
end LogN7
