import LogN7.Case1.Data
/-! log kernel, Case 1: `Blk.ok` of the S-block S0.

Generated by `lean/gen_log/emit_cert3.py` from `cert_case1_log_D10.json`
(sha256 d50793adbadf05c191e9c0f39ea08d4739399df89e22598252ed086d63a7b3ae).  Do not edit; regenerate. -/

namespace LogN7
namespace Case1
open ThomsonN7.Cert ThomsonN7.Cert.Cert3
theorem r2c1_blk_S0 : LogN7.Case1Data.S0.B.ok LogN7.Case1Data.S0.z.length = true := by
  decide +kernel
end Case1
end LogN7
