import LogN7.Case1.Data
/-! log kernel, Case 1: `Blk.ok` of the S-blocks S1..S7, one `decide +kernel` per block.

Generated by `lean/gen_log/emit_cert3.py` from `cert_case1_log_D10.json`
(sha256 d50793adbadf05c191e9c0f39ea08d4739399df89e22598252ed086d63a7b3ae).  Do not edit; regenerate. -/

namespace LogN7
namespace Case1
open ThomsonN7.Cert ThomsonN7.Cert.Cert3
theorem r2c1_blk_S1 : LogN7.Case1Data.S1.B.ok LogN7.Case1Data.S1.z.length = true := by
  decide +kernel

theorem r2c1_blk_S2 : LogN7.Case1Data.S2.B.ok LogN7.Case1Data.S2.z.length = true := by
  decide +kernel

theorem r2c1_blk_S3 : LogN7.Case1Data.S3.B.ok LogN7.Case1Data.S3.z.length = true := by
  decide +kernel

theorem r2c1_blk_S4 : LogN7.Case1Data.S4.B.ok LogN7.Case1Data.S4.z.length = true := by
  decide +kernel

theorem r2c1_blk_S5 : LogN7.Case1Data.S5.B.ok LogN7.Case1Data.S5.z.length = true := by
  decide +kernel

theorem r2c1_blk_S6 : LogN7.Case1Data.S6.B.ok LogN7.Case1Data.S6.z.length = true := by
  decide +kernel

theorem r2c1_blk_S7 : LogN7.Case1Data.S7.B.ok LogN7.Case1Data.S7.z.length = true := by
  decide +kernel
end Case1
end LogN7
