import LogN7.Case1.Data
/-! log kernel, Case 1: `Blk.ok` of the F-blocks, one `decide +kernel` per block.

Generated by `lean/gen_log/emit_cert3.py` from `cert_case1_log_D10.json`
(sha256 d50793adbadf05c191e9c0f39ea08d4739399df89e22598252ed086d63a7b3ae).  Do not edit; regenerate. -/

namespace LogN7
namespace Case1
open ThomsonN7.Cert ThomsonN7.Cert.Cert3
theorem r2c1_blk_F0 : (LogN7.Case1Data.cf.blk 0).ok (LogN7.Case1Data.cf.m 0) = true := by
  decide +kernel

theorem r2c1_blk_F1 : (LogN7.Case1Data.cf.blk 1).ok (LogN7.Case1Data.cf.m 1) = true := by
  decide +kernel

theorem r2c1_blk_F2 : (LogN7.Case1Data.cf.blk 2).ok (LogN7.Case1Data.cf.m 2) = true := by
  decide +kernel

theorem r2c1_blk_F3 : (LogN7.Case1Data.cf.blk 3).ok (LogN7.Case1Data.cf.m 3) = true := by
  decide +kernel
end Case1
end LogN7
