import ThomsonGen.Case1Stat
import LogN7.Case1.Data
/-! log kernel, Case 1: statistics machinery for the chunked Kronecker check.

Upstream's `ThomsonN7.Case1.c1Stat` (one structural pass computing `(ℓ¹, deg u, deg v, deg t, kev)`),
`c1Stat_eq`, `c1FtotK` and the composition lemma `c1Stat_idE` (module `ThomsonGen.Case1Stat`) are
data-independent (they import only `Cert3`) and are reused verbatim.  For this certificate the
Kronecker parameters of `Cert.chk` are `w = Nat.log2 ℓ¹ + 1 = 108` and `D = max deg + 1 = 11`.

Generated by `lean/gen_log/emit_cert3.py` from `cert_case1_log_D10.json`
(sha256 d50793adbadf05c191e9c0f39ea08d4739399df89e22598252ed086d63a7b3ae).  Do not edit; regenerate. -/
