import LogN7.Cap.ChkMeta
import LogN7.Cap.ChkA
import LogN7.Cap.ChkB
import LogN7.Cap.ChkG
import LogN7.Bridge
import LogN7.Minor.MinorCap
/-! Cap: `ThomsonGen.CapSpec φ₀ (1/1650) (-99/100)` from the checked facially reduced
certificate `tc_cap` (`Cert.TCertN`, re-rounded, NOT exactly sharp: E(P) − ef = 7.294e-17 ≤ δ = 10⁻¹⁶)
and the coercive minorants of `LogLean.Minor.Cap` (identified through `scaledEq`).
Generated by lean/gen_log/gen_spec_log.py; do not edit. -/

open Real
namespace LogN7
namespace Cap
open ThomsonN7 ThomsonN7.Cert ThomsonGen

theorem e_eq : tc_cap.toTCert.e = -31890058149644122262049354940416000000 := rfl
theorem lam_eq : tc_cap.toTCert.Lam = 3897359538021488729658557988864000000 := rfl
theorem an_eq : tc_cap.toTCert.an = -1 := rfl
theorem ad_eq : tc_cap.toTCert.ad = 1 := rfl
theorem bn_eq : tc_cap.toTCert.bn = -99 := rfl
theorem bd_eq : tc_cap.toTCert.bd = 100 := rfl
theorem lam_pos : 0 < tc_cap.toTCert.Lam := by rw [lam_eq]; norm_num
theorem alo_eq : tc_cap.toTCert.alo = -1 := by
  unfold TCert.alo; rw [an_eq, ad_eq]; norm_num
theorem ahi_eq : tc_cap.toTCert.ahi = (-99 / 100 : ℝ) := by
  unfold TCert.ahi; rw [bn_eq, bd_eq]; norm_num
/-- `E(P) ≤ ef + δ`, `δ = 10⁻¹⁶`. -/
theorem ef_ge : pairEnergy LogLean.Minor.phi pentBipyramid ≤ tc_cap.toTCert.ef + 1 / 10 ^ 16 := by
  refine pairEnergy_pent_le.trans ?_
  unfold TCert.ef; rw [e_eq, lam_eq]; norm_num
theorem eA : scaledEq LogLean.Minor.Cap.HdA tc_cap.toTCert.HA tc_cap.toTCert.Lam LogLean.Minor.Cap.HA = true := by decide +kernel
theorem eB : scaledEq LogLean.Minor.Cap.HdB tc_cap.toTCert.HB tc_cap.toTCert.Lam LogLean.Minor.Cap.HB = true := by decide +kernel
theorem eC : scaledEq LogLean.Minor.Cap.HdC tc_cap.toTCert.HC tc_cap.toTCert.Lam LogLean.Minor.Cap.HC = true := by decide +kernel

/-- **The log cap**. -/
theorem spec : CapSpec LogLean.Minor.phi (1 / 1650) (-99 / 100 : ℝ) :=
  capSpec_of_minorN tc_cap tc_cap_meta tc_cap_A tc_cap_B tc_cap_G alo_eq ahi_eq ef_ge lam_pos
    (by decide) (by decide) (by decide) eA eB eC
    (fun t h1 h2 => LogLean.Minor.Cap.capA h1 h2) (fun t h1 h2 => LogLean.Minor.Cap.capB h1 h2)
    (fun t h1 h2 => LogLean.Minor.Cap.capC h1 h2)

end Cap
end LogN7
