import LogN7.S9694.ChkMeta
import LogN7.S9694.ChkA
import LogN7.S9694.ChkB
import LogN7.S9694.ChkG
import LogN7.Bridge
import LogN7.Minor.MinorSlab9694
/-! Slab S9694: `ThomsonGen.SlabSpec φ₀ -24/25 -47/50` from the checked packed certificate `tc_s9694` and the 1-D
minorants of `LogLean.Minor.CellSlab9694` (identified through `scaledEq`).  Generated by lean/gen_log/gen_spec_log.py; do not edit. -/

open Real
namespace LogN7
namespace S9694
open ThomsonN7 ThomsonN7.Cert ThomsonGen

theorem e_eq : tc_s9694.e = -150939152717005291520 := rfl
theorem lam_eq : tc_s9694.Lam = 18446744073709551616 := rfl
theorem an_eq : tc_s9694.an = -24 := rfl
theorem ad_eq : tc_s9694.ad = 25 := rfl
theorem bn_eq : tc_s9694.bn = -47 := rfl
theorem bd_eq : tc_s9694.bd = 50 := rfl
theorem lam_pos : 0 < tc_s9694.Lam := by rw [lam_eq]; norm_num
theorem alo_eq : tc_s9694.alo = (-24 / 25 : ℝ) := by
  unfold TCert.alo; rw [an_eq, ad_eq]; norm_num
theorem ahi_eq : tc_s9694.ahi = (-47 / 50 : ℝ) := by
  unfold TCert.ahi; rw [bn_eq, bd_eq]; norm_num
/-- `E(P) < ef` (margin 5.000e-05). -/
theorem ef_gt : pairEnergy LogLean.Minor.phi pentBipyramid < tc_s9694.ef := by
  refine lt_of_le_of_lt pairEnergy_pent_le ?_
  unfold TCert.ef; rw [e_eq, lam_eq]; norm_num
theorem eA : scaledEq LogLean.Minor.CellSlab9694.HdA tc_s9694.HA tc_s9694.Lam LogLean.Minor.CellSlab9694.HA = true := by decide +kernel
theorem eB : scaledEq LogLean.Minor.CellSlab9694.HdB tc_s9694.HB tc_s9694.Lam LogLean.Minor.CellSlab9694.HB = true := by decide +kernel
theorem eC : scaledEq LogLean.Minor.CellSlab9694.HdC tc_s9694.HC tc_s9694.Lam LogLean.Minor.CellSlab9694.HC = true := by decide +kernel
theorem hD : (LogLean.Minor.CellSlab9694.D : ℝ) = 409600 := by norm_num [LogLean.Minor.CellSlab9694.D]

/-- **Slab S9694.** -/
theorem spec : SlabSpec LogLean.Minor.phi (-24 / 25 : ℝ) (-47 / 50 : ℝ) :=
  slabSpec_of_minor tc_s9694 tc_s9694_meta tc_s9694_A tc_s9694_B tc_s9694_G alo_eq ahi_eq ef_gt lam_pos
    (by decide) (by decide) (by decide) eA eB eC
    (fun t h1 h2 => LogLean.Minor.CellSlab9694.HA_le_phi (by rw [hD]; push_cast; linarith) (by rw [hD]; push_cast; linarith))
    (fun t h1 h2 => LogLean.Minor.CellSlab9694.HB_le_phi (by rw [hD]; push_cast; linarith) h2)
    (fun t h1 h2 => LogLean.Minor.CellSlab9694.HC_le_phi (by rw [hD]; push_cast; linarith) h2)

end S9694
end LogN7
